//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommAmbientNoiseJSON.hh"


namespace DomainSpeechIDL {

void to_json(const DomainSpeechIDL::CommAmbientNoise& obj, nlohmann::json& j)
{
	// noise_level: UInt32
	j["noise_level"] = obj.noise_level;
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, DomainSpeechIDL::CommAmbientNoise& obj)
{
	// noise_level: UInt32
	if(j.contains("noise_level") && j["noise_level"].is_number_unsigned()) {
		obj.noise_level = j["noise_level"].get<unsigned int>();
	}
}

} // end namespace DomainSpeechIDL
