//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMTRACKINGOBJECTS_COMMDETECTEDMARKEREVENTPARAMETER_CORE_H_
#define COMMTRACKINGOBJECTS_COMMDETECTEDMARKEREVENTPARAMETER_CORE_H_

#include "CommTrackingObjects/CommDetectedMarkerEventParameterData.hh"
#include "CommTrackingObjects/CommDetectedMarkerList.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommTrackingObjects {
	
class CommDetectedMarkerEventParameterCore {
protected:
	// data structure
	CommTrackingObjectsIDL::CommDetectedMarkerEventParameter idl_CommDetectedMarkerEventParameter;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommTrackingObjectsIDL::CommDetectedMarkerEventParameter DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommDetectedMarkerEventParameterCore();
	CommDetectedMarkerEventParameterCore(const DATATYPE &data);
	// default destructor
	virtual ~CommDetectedMarkerEventParameterCore();
	
	const DATATYPE& get() const { return idl_CommDetectedMarkerEventParameter; }
	operator const DATATYPE&() const { return idl_CommDetectedMarkerEventParameter; }
	DATATYPE& set() { return idl_CommDetectedMarkerEventParameter; }

	static inline std::string identifier(void) { return "CommTrackingObjects::CommDetectedMarkerEventParameter"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Markers
	inline CommTrackingObjects::CommDetectedMarkerList getMarkers() const { return CommTrackingObjects::CommDetectedMarkerList(idl_CommDetectedMarkerEventParameter.markers); }
	inline CommDetectedMarkerEventParameterCore& setMarkers(const CommTrackingObjects::CommDetectedMarkerList &markers) { idl_CommDetectedMarkerEventParameter.markers = markers; return *this; }
};

} /* namespace CommTrackingObjects */
#endif /* COMMTRACKINGOBJECTS_COMMDETECTEDMARKEREVENTPARAMETER_CORE_H_ */
