//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMTRACKINGOBJECTS_SCANPARAM_ENUM_H_
#define COMMTRACKINGOBJECTS_SCANPARAM_ENUM_H_

#include <CommTrackingObjects/enumScanParamData.hh>

#include <string>
#include <iostream>
#include <locale>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace CommTrackingObjects {
	
	class ScanParam {
	private:
		CommTrackingObjectsIDL::ScanParam value;
		
	public:
		enum ENUM_ScanParam {
			ENUM_VALUE_UNDEFINED = 0,
			NONE_SCAN_PARAM = 1,
			FULL_SCAN_PARAM = 2
		};
		
		// default constructor
		ScanParam() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		ScanParam(ENUM_ScanParam e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type (which is typically int)
		ScanParam(CommTrackingObjectsIDL::ScanParam e) {
			value = e;
		}
		
		//const CommTrackingObjectsIDL::ScanParam& get() const { return value; }
		
		// ENUM operator
		operator ENUM_ScanParam() const {
			return static_cast<ENUM_ScanParam>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_ScanParam t) const {
			return this->value == t;
		}
		
		std::string to_string(const bool &use_fqn=true) const {
			std::string result = "";
			if(use_fqn == true) {
				result = "ScanParam::";
			}
			switch (value) {
				case NONE_SCAN_PARAM:
					result += "NONE_SCAN_PARAM";
					break;
				case FULL_SCAN_PARAM:
					result += "FULL_SCAN_PARAM";
					break;
				default:
					result += "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		static ScanParam from_string(const std::string &value) {
			std::string input = value;
			std::locale l;
			for(auto &c: input) {
				// convert all characters to lower case (so string comparison works regardless of small/capital letters)
				c = std::tolower(c,l);
			}
			std::string base_name = "scanparam::";
			if(input.compare(0, base_name.length(), base_name) == 0) {
				// remove basename from comparing the actual enumeration
				input.erase(0,base_name.length());
			}
			if(input == "none_scan_param"){
				return ScanParam(NONE_SCAN_PARAM);
			}
			if(input == "full_scan_param"){
				return ScanParam(FULL_SCAN_PARAM);
			}
			// default (if none of the preceding options match)
			return ScanParam();
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const ScanParam &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
