//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommNavigationObjects/CommBundledNavigationEventParameterCore.hh"

// serialization/deserialization operators
//#include "CommNavigationObjects/CommBundledNavigationEventParameterACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace CommNavigationObjects 
{
	const char* CommBundledNavigationEventParameterCore::getCompiledHash()
	{
		return CommNavigationObjectsIDL::REPO_HASH;
	}
	
	void CommBundledNavigationEventParameterCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
	}
	
	void CommBundledNavigationEventParameterCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommBundledNavigationEventParameterCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
	}
	
	#ifdef ENABLE_HASH
	size_t CommBundledNavigationEventParameterCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		boost::hash_combine(seed, std::string(data.locationName.c_str()));
		boost::hash_combine(seed, data.previousState);
		
		return seed;
	}
	#endif
	
	// default constructor
	CommBundledNavigationEventParameterCore::CommBundledNavigationEventParameterCore()
	:	idl_CommBundledNavigationEventParameter()
	{  
		setLocationName("");
		setPreviousState(CommNavigationObjects::BundledNavigationGoalState());
	}
	
	CommBundledNavigationEventParameterCore::CommBundledNavigationEventParameterCore(const DATATYPE &data)
	:	idl_CommBundledNavigationEventParameter(data)
	{  }

	CommBundledNavigationEventParameterCore::~CommBundledNavigationEventParameterCore()
	{  }
	
	void CommBundledNavigationEventParameterCore::to_ostream(std::ostream &os) const
	{
	  os << "CommBundledNavigationEventParameter(";
	  os << getLocationName() << " ";
	  getPreviousState().to_ostream(os);
	  os << ") ";
	}
	
	// convert to xml stream
	void CommBundledNavigationEventParameterCore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<locationName>" << getLocationName() << "</locationName>";
		os << indent << "<previousState>";
		getPreviousState().to_xml(os, indent);
		os << indent << "</previousState>";
	}
	
	// restore from xml stream
	void CommBundledNavigationEventParameterCore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_locationName("<locationName>");
		static const Smart::KnuthMorrisPratt kmp_previousState("<previousState>");
		
		if(kmp_locationName.search(is)) {
			std::string locationNameItem;
			is >> locationNameItem;
			setLocationName(locationNameItem);
		}
		if(kmp_previousState.search(is)) {
			CommNavigationObjects::BundledNavigationGoalState previousStateItem;
			previousStateItem.from_xml(is);
			setPreviousState(previousStateItem);
		}
	}
	
	/*
	void CommBundledNavigationEventParameterCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		CommNavigationObjectsIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(CommNavigationObjectsIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommBundledNavigationEventParameterACE.hh)
		cdr << idl_CommBundledNavigationEventParameter;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommBundledNavigationEventParameter);
		cdr << data_hash;
		// std::cout << "CommBundledNavigationEventParameterCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommBundledNavigationEventParameterCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		CommNavigationObjectsIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommBundledNavigationEventParameterACE.hh)
		cdr >> idl_CommBundledNavigationEventParameter;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommBundledNavigationEventParameter);
		assert(data_hash == own_hash);
		// std::cout << "CommBundledNavigationEventParameterCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace CommNavigationObjects */
