//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMNAVIGATIONOBJECTS_COMMBUNDLEDNAVIGATIONEVENTSTATE_CORE_H_
#define COMMNAVIGATIONOBJECTS_COMMBUNDLEDNAVIGATIONEVENTSTATE_CORE_H_

#include "CommNavigationObjects/CommBundledNavigationEventStateData.hh"
#include "CommNavigationObjects/enumBundledNavigationGoalState.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommNavigationObjects {
	
class CommBundledNavigationEventStateCore {
protected:
	// data structure
	CommNavigationObjectsIDL::CommBundledNavigationEventState idl_CommBundledNavigationEventState;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommNavigationObjectsIDL::CommBundledNavigationEventState DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommBundledNavigationEventStateCore();
	CommBundledNavigationEventStateCore(const DATATYPE &data);
	// default destructor
	virtual ~CommBundledNavigationEventStateCore();
	
	const DATATYPE& get() const { return idl_CommBundledNavigationEventState; }
	operator const DATATYPE&() const { return idl_CommBundledNavigationEventState; }
	DATATYPE& set() { return idl_CommBundledNavigationEventState; }

	static inline std::string identifier(void) { return "CommNavigationObjects::CommBundledNavigationEventState"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element LocationName
	inline std::string getLocationName() const { return idl_CommBundledNavigationEventState.locationName; }
	inline CommBundledNavigationEventStateCore& setLocationName(const std::string &locationName) { idl_CommBundledNavigationEventState.locationName = locationName; return *this; }
	
	// getter and setter for element GoalState
	inline CommNavigationObjects::BundledNavigationGoalState getGoalState() const { return CommNavigationObjects::BundledNavigationGoalState(idl_CommBundledNavigationEventState.goalState); }
	inline CommBundledNavigationEventStateCore& setGoalState(const CommNavigationObjects::BundledNavigationGoalState &goalState) { idl_CommBundledNavigationEventState.goalState = goalState; return *this; }
};

} /* namespace CommNavigationObjects */
#endif /* COMMNAVIGATIONOBJECTS_COMMBUNDLEDNAVIGATIONEVENTSTATE_CORE_H_ */
