//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommNavigationObjects/CommBundledNavigationEventResultACE.hh"
#include <ace/SString.h>
#include "CommNavigationObjects/enumBundledNavigationGoalStateData.hh"

// serialization operator for element CommBundledNavigationEventResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommNavigationObjectsIDL::CommBundledNavigationEventResult &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element locationName
	good_bit = good_bit && cdr << ACE_CString(data.locationName.c_str());
	// serialize list-element goalState
	good_bit = good_bit && cdr.write_long(data.goalState);
	
	return good_bit;
}

// de-serialization operator for element CommBundledNavigationEventResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommNavigationObjectsIDL::CommBundledNavigationEventResult &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize string-type element locationName
	ACE_CString data_locationName_str;
	good_bit = good_bit && cdr >> data_locationName_str;
	data.locationName = data_locationName_str.c_str();
	// deserialize type element goalState
	good_bit = good_bit && cdr.read_long(data.goalState);
	
	return good_bit;
}

// serialization operator for CommunicationObject CommBundledNavigationEventResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommNavigationObjects::CommBundledNavigationEventResult &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommBundledNavigationEventResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommNavigationObjects::CommBundledNavigationEventResult &obj)
{
	return cdr >> obj.set();
}
