//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMNAVIGATIONOBJECTS_CDLROBOTBLOCKEVENTTYPE_ENUM_H_
#define COMMNAVIGATIONOBJECTS_CDLROBOTBLOCKEVENTTYPE_ENUM_H_

#include <CommNavigationObjects/enumCdlRobotBlockEventTypeData.hh>

#include <string>
#include <iostream>
#include <locale>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace CommNavigationObjects {
	
	class CdlRobotBlockEventType {
	private:
		CommNavigationObjectsIDL::CdlRobotBlockEventType value;
		
	public:
		enum ENUM_CdlRobotBlockEventType {
			ENUM_VALUE_UNDEFINED = 0,
			CDL_ROBOT_UNKNOWN = 1,
			CDL_ROBOT_BLOCKED = 2,
			CDL_ROBOT_NOT_BLOCKED = 3,
			CDL_ROBOT_BLOCKED_PATH = 4,
			CDL_ROBOT_UNBLOCKED_PATH = 5
		};
		
		// default constructor
		CdlRobotBlockEventType() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		CdlRobotBlockEventType(ENUM_CdlRobotBlockEventType e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type (which is typically int)
		CdlRobotBlockEventType(CommNavigationObjectsIDL::CdlRobotBlockEventType e) {
			value = e;
		}
		
		//const CommNavigationObjectsIDL::CdlRobotBlockEventType& get() const { return value; }
		
		// ENUM operator
		operator ENUM_CdlRobotBlockEventType() const {
			return static_cast<ENUM_CdlRobotBlockEventType>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_CdlRobotBlockEventType t) const {
			return this->value == t;
		}
		
		std::string to_string(const bool &use_fqn=true) const {
			std::string result = "";
			if(use_fqn == true) {
				result = "CdlRobotBlockEventType::";
			}
			switch (value) {
				case CDL_ROBOT_UNKNOWN:
					result += "CDL_ROBOT_UNKNOWN";
					break;
				case CDL_ROBOT_BLOCKED:
					result += "CDL_ROBOT_BLOCKED";
					break;
				case CDL_ROBOT_NOT_BLOCKED:
					result += "CDL_ROBOT_NOT_BLOCKED";
					break;
				case CDL_ROBOT_BLOCKED_PATH:
					result += "CDL_ROBOT_BLOCKED_PATH";
					break;
				case CDL_ROBOT_UNBLOCKED_PATH:
					result += "CDL_ROBOT_UNBLOCKED_PATH";
					break;
				default:
					result += "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		static CdlRobotBlockEventType from_string(const std::string &value) {
			std::string input = value;
			std::locale l;
			for(auto &c: input) {
				// convert all characters to lower case (so string comparison works regardless of small/capital letters)
				c = std::tolower(c,l);
			}
			std::string base_name = "cdlrobotblockeventtype::";
			if(input.compare(0, base_name.length(), base_name) == 0) {
				// remove basename from comparing the actual enumeration
				input.erase(0,base_name.length());
			}
			if(input == "cdl_robot_unknown"){
				return CdlRobotBlockEventType(CDL_ROBOT_UNKNOWN);
			}
			if(input == "cdl_robot_blocked"){
				return CdlRobotBlockEventType(CDL_ROBOT_BLOCKED);
			}
			if(input == "cdl_robot_not_blocked"){
				return CdlRobotBlockEventType(CDL_ROBOT_NOT_BLOCKED);
			}
			if(input == "cdl_robot_blocked_path"){
				return CdlRobotBlockEventType(CDL_ROBOT_BLOCKED_PATH);
			}
			if(input == "cdl_robot_unblocked_path"){
				return CdlRobotBlockEventType(CDL_ROBOT_UNBLOCKED_PATH);
			}
			// default (if none of the preceding options match)
			return CdlRobotBlockEventType();
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const CdlRobotBlockEventType &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
