//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINROBOTFLEETNAVIGATION_COMMCORRIDORPATH_H_
#define DOMAINROBOTFLEETNAVIGATION_COMMCORRIDORPATH_H_

#include "DomainRobotFleetNavigation/CommCorridorPathCore.hh"

namespace DomainRobotFleetNavigation {
		
class CommCorridorPath : public CommCorridorPathCore {
	public:
		// default constructors
		CommCorridorPath();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommCorridorPath(const std::vector<DomainRobotFleetNavigation::CommNode> &nodes, const std::vector<double> &widths);
		
		CommCorridorPath(const CommCorridorPathCore &commCorridorPath);
		CommCorridorPath(const DATATYPE &commCorridorPath);
		virtual ~CommCorridorPath();
		
		// use framework specific getter and setter methods from core (base) class
		using CommCorridorPathCore::get;
		using CommCorridorPathCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommCorridorPath &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace DomainRobotFleetNavigation */
#endif /* DOMAINROBOTFLEETNAVIGATION_COMMCORRIDORPATH_H_ */
