//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommLaserTrackingDataJSON.hh"

#include "CommBasicObjectsJSON/CommMobileLaserScanJSON.hh"
#include "CommTrackingObjectsJSON/CommLaserTrackedObjectJSON.hh"

namespace CommTrackingObjectsIDL {

void to_json(const CommTrackingObjectsIDL::CommLaserTrackingData& obj, nlohmann::json& j)
{
	// scan: CommMobileLaserScan
	to_json(obj.scan, j["scan"]);
	// objects: CommLaserTrackedObject[]
	for(size_t idx=0; idx < obj.objects.size(); idx++) {
		nlohmann::json array_element;
		to_json(obj.objects.at(idx), array_element);
		j["objects"].emplace_back(array_element);
	}
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, CommTrackingObjectsIDL::CommLaserTrackingData& obj)
{
	// scan: CommMobileLaserScan
	if(j.contains("scan") && j["scan"].is_object()) {
		//from_json(j["scan"], obj.scan);
		obj.scan = j["scan"].get<CommBasicObjectsIDL::CommMobileLaserScan>();
	}
	// objects: CommLaserTrackedObject[]
	if(j.contains("objects") && j["objects"].is_array()) {
		auto jobjects = j["objects"];
		obj.objects.resize(jobjects.size());
		for(size_t idx=0; idx < jobjects.size(); idx++) {
			// convert the json array values individually
			if(jobjects.at(idx).is_object()) {
				// from_json(jobjects.at(idx), obj.objects.at(idx));
				obj.objects[idx] = jobjects[idx].get<CommTrackingObjectsIDL::CommLaserTrackedObject>();
			}
		}
	}
}

} // end namespace CommTrackingObjectsIDL
