//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommPrintRequestJSON.hh"

#include "DomainPrintJSON/CommPrintDataJSON.hh"

namespace DomainPrintIDL {

void to_json(const DomainPrintIDL::CommPrintRequest& obj, nlohmann::json& j)
{
	// data: CommPrintData
	to_json(obj.data, j["data"]);
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, DomainPrintIDL::CommPrintRequest& obj)
{
	// data: CommPrintData
	if(j.contains("data") && j["data"].is_object()) {
		//from_json(j["data"], obj.data);
		obj.data = j["data"].get<DomainPrintIDL::CommPrintData>();
	}
}

} // end namespace DomainPrintIDL
