//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommKeyValueJSON.hh"

#include <DomainPrint/enumKeyValueDataTypeEnum.hh>

namespace DomainPrintIDL {

void to_json(const DomainPrintIDL::CommKeyValue& obj, nlohmann::json& j)
{
	// key: String
	j["key"] = obj.key;
	// value: String
	j["value"] = obj.value;
	// type: KeyValueDataTypeEnum
	j["type"] = DomainPrint::KeyValueDataTypeEnum(obj.type).to_string(false);
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, DomainPrintIDL::CommKeyValue& obj)
{
	// key: String
	if(j.contains("key") && j["key"].is_string()) {
		obj.key = j["key"].get<std::string>();
	}
	// value: String
	if(j.contains("value") && j["value"].is_string()) {
		obj.value = j["value"].get<std::string>();
	}
	// type: KeyValueDataTypeEnum
	if(j.contains("type") && j["type"].is_string()) {
		obj.type = DomainPrint::KeyValueDataTypeEnum::from_string(j["type"].get<std::string>());
	}
}

} // end namespace DomainPrintIDL
