//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommPrintDataJSON.hh"


namespace DomainPrintIDL {

void to_json(const DomainPrintIDL::CommPrintData& obj, nlohmann::json& j)
{
	// data: String
	j["data"] = obj.data;
	// format: PrintDataEnum
	j["format"] = obj.format;
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, DomainPrintIDL::CommPrintData& obj)
{
	// data: String
	if(j.contains("data") && j["data"].is_string()) {
		obj.data = j["data"].get<std::string>();
	}
	// format: PrintDataEnum
	if(j.contains("format") && j["format"].is_number_integer()) {
		obj.format = j["format"].get<int>();
	}
}

} // end namespace DomainPrintIDL
