//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainVision/CommDisparityImageCore.hh"

// serialization/deserialization operators
//#include "DomainVision/CommDisparityImageACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace DomainVision 
{
	const char* CommDisparityImageCore::getCompiledHash()
	{
		return DomainVisionIDL::REPO_HASH;
	}
	
	void CommDisparityImageCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
		// get hash value(s) for DomainVision::CommVideoImage(idl_CommDisparityImage.image)
		DomainVision::CommVideoImage::getAllHashValues(hashes);
		// get hash value(s) for DomainVision::CommImageRegionOfInterest(idl_CommDisparityImage.valid_window)
		DomainVision::CommImageRegionOfInterest::getAllHashValues(hashes);
	}
	
	void CommDisparityImageCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommDisparityImageCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
		// check hash value(s) for DomainVision::CommVideoImage(idl_CommDisparityImage.image)
		DomainVision::CommVideoImage::checkAllHashValues(hashes);
		// check hash value(s) for DomainVision::CommImageRegionOfInterest(idl_CommDisparityImage.valid_window)
		DomainVision::CommImageRegionOfInterest::checkAllHashValues(hashes);
	}
	
	#ifdef ENABLE_HASH
	size_t CommDisparityImageCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		seed += DomainVision::CommVideoImage::generateDataHash(data.image);
		boost::hash_combine(seed, data.f);
		boost::hash_combine(seed, data.t);
		seed += DomainVision::CommImageRegionOfInterest::generateDataHash(data.valid_window);
		boost::hash_combine(seed, data.min_disparity);
		boost::hash_combine(seed, data.max_disparity);
		boost::hash_combine(seed, data.delta_d);
		
		return seed;
	}
	#endif
	
	// default constructor
	CommDisparityImageCore::CommDisparityImageCore()
	:	idl_CommDisparityImage()
	{  
		setImage(DomainVision::CommVideoImage());
		setF(0.0);
		setT(0.0);
		setValid_window(DomainVision::CommImageRegionOfInterest());
		setMin_disparity(0.0);
		setMax_disparity(0.0);
		setDelta_d(0.0);
	}
	
	CommDisparityImageCore::CommDisparityImageCore(const DATATYPE &data)
	:	idl_CommDisparityImage(data)
	{  }

	CommDisparityImageCore::~CommDisparityImageCore()
	{  }
	
	void CommDisparityImageCore::to_ostream(std::ostream &os) const
	{
	  os << "CommDisparityImage(";
	  getImage().to_ostream(os);
	  os << getF() << " ";
	  os << getT() << " ";
	  getValid_window().to_ostream(os);
	  os << getMin_disparity() << " ";
	  os << getMax_disparity() << " ";
	  os << getDelta_d() << " ";
	  os << ") ";
	}
	
	// convert to xml stream
	void CommDisparityImageCore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<image>";
		getImage().to_xml(os, indent);
		os << indent << "</image>";
		os << indent << "<f>" << getF() << "</f>";
		os << indent << "<t>" << getT() << "</t>";
		os << indent << "<valid_window>";
		getValid_window().to_xml(os, indent);
		os << indent << "</valid_window>";
		os << indent << "<min_disparity>" << getMin_disparity() << "</min_disparity>";
		os << indent << "<max_disparity>" << getMax_disparity() << "</max_disparity>";
		os << indent << "<delta_d>" << getDelta_d() << "</delta_d>";
	}
	
	// restore from xml stream
	void CommDisparityImageCore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_image("<image>");
		static const Smart::KnuthMorrisPratt kmp_f("<f>");
		static const Smart::KnuthMorrisPratt kmp_t("<t>");
		static const Smart::KnuthMorrisPratt kmp_valid_window("<valid_window>");
		static const Smart::KnuthMorrisPratt kmp_min_disparity("<min_disparity>");
		static const Smart::KnuthMorrisPratt kmp_max_disparity("<max_disparity>");
		static const Smart::KnuthMorrisPratt kmp_delta_d("<delta_d>");
		
		if(kmp_image.search(is)) {
			DomainVision::CommVideoImage imageItem;
			imageItem.from_xml(is);
			setImage(imageItem);
		}
		if(kmp_f.search(is)) {
			float fItem;
			is >> fItem;
			setF(fItem);
		}
		if(kmp_t.search(is)) {
			float tItem;
			is >> tItem;
			setT(tItem);
		}
		if(kmp_valid_window.search(is)) {
			DomainVision::CommImageRegionOfInterest valid_windowItem;
			valid_windowItem.from_xml(is);
			setValid_window(valid_windowItem);
		}
		if(kmp_min_disparity.search(is)) {
			float min_disparityItem;
			is >> min_disparityItem;
			setMin_disparity(min_disparityItem);
		}
		if(kmp_max_disparity.search(is)) {
			float max_disparityItem;
			is >> max_disparityItem;
			setMax_disparity(max_disparityItem);
		}
		if(kmp_delta_d.search(is)) {
			float delta_dItem;
			is >> delta_dItem;
			setDelta_d(delta_dItem);
		}
	}
	
	/*
	void CommDisparityImageCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		DomainVisionIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(DomainVisionIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommDisparityImageACE.hh)
		cdr << idl_CommDisparityImage;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommDisparityImage);
		cdr << data_hash;
		// std::cout << "CommDisparityImageCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommDisparityImageCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		DomainVisionIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommDisparityImageACE.hh)
		cdr >> idl_CommDisparityImage;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommDisparityImage);
		assert(data_hash == own_hash);
		// std::cout << "CommDisparityImageCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace DomainVision */
