//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINVISION_COMMSTEREOIMAGE_ACE_H_
#define DOMAINVISION_COMMSTEREOIMAGE_ACE_H_

#include "DomainVision/CommStereoImage.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure CommStereoImage
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainVisionIDL::CommStereoImage &data);

// de-serialization operator for DataStructure CommStereoImage
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainVisionIDL::CommStereoImage &data);

// serialization operator for CommunicationObject CommStereoImage
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainVision::CommStereoImage &obj);

// de-serialization operator for CommunicationObject CommStereoImage
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainVision::CommStereoImage &obj);

#endif /* DOMAINVISION_COMMSTEREOIMAGE_ACE_H_ */
