//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINVISION_COMMDISPARITYIMAGE_CORE_H_
#define DOMAINVISION_COMMDISPARITYIMAGE_CORE_H_

#include "DomainVision/CommDisparityImageData.hh"
#include "DomainVision/CommVideoImage.hh"
#include "DomainVision/CommImageRegionOfInterest.hh"

#include <iostream>
#include <string>
#include <list>

namespace DomainVision {
	
class CommDisparityImageCore {
protected:
	// data structure
	DomainVisionIDL::CommDisparityImage idl_CommDisparityImage;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef DomainVisionIDL::CommDisparityImage DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommDisparityImageCore();
	CommDisparityImageCore(const DATATYPE &data);
	// default destructor
	virtual ~CommDisparityImageCore();
	
	const DATATYPE& get() const { return idl_CommDisparityImage; }
	operator const DATATYPE&() const { return idl_CommDisparityImage; }
	DATATYPE& set() { return idl_CommDisparityImage; }

	static inline std::string identifier(void) { return "DomainVision::CommDisparityImage"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Image
	inline DomainVision::CommVideoImage getImage() const { return DomainVision::CommVideoImage(idl_CommDisparityImage.image); }
	inline CommDisparityImageCore& setImage(const DomainVision::CommVideoImage &image) { idl_CommDisparityImage.image = image; return *this; }
	
	// getter and setter for element F
	inline float getF() const { return idl_CommDisparityImage.f; }
	inline CommDisparityImageCore& setF(const float &f) { idl_CommDisparityImage.f = f; return *this; }
	
	// getter and setter for element T
	inline float getT() const { return idl_CommDisparityImage.t; }
	inline CommDisparityImageCore& setT(const float &t) { idl_CommDisparityImage.t = t; return *this; }
	
	// getter and setter for element Valid_window
	inline DomainVision::CommImageRegionOfInterest getValid_window() const { return DomainVision::CommImageRegionOfInterest(idl_CommDisparityImage.valid_window); }
	inline CommDisparityImageCore& setValid_window(const DomainVision::CommImageRegionOfInterest &valid_window) { idl_CommDisparityImage.valid_window = valid_window; return *this; }
	
	// getter and setter for element Min_disparity
	inline float getMin_disparity() const { return idl_CommDisparityImage.min_disparity; }
	inline CommDisparityImageCore& setMin_disparity(const float &min_disparity) { idl_CommDisparityImage.min_disparity = min_disparity; return *this; }
	
	// getter and setter for element Max_disparity
	inline float getMax_disparity() const { return idl_CommDisparityImage.max_disparity; }
	inline CommDisparityImageCore& setMax_disparity(const float &max_disparity) { idl_CommDisparityImage.max_disparity = max_disparity; return *this; }
	
	// getter and setter for element Delta_d
	inline float getDelta_d() const { return idl_CommDisparityImage.delta_d; }
	inline CommDisparityImageCore& setDelta_d(const float &delta_d) { idl_CommDisparityImage.delta_d = delta_d; return *this; }
};

} /* namespace DomainVision */
#endif /* DOMAINVISION_COMMDISPARITYIMAGE_CORE_H_ */
