//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINVISION_DEPTHFORMATTYPE_ENUM_H_
#define DOMAINVISION_DEPTHFORMATTYPE_ENUM_H_

#include <DomainVision/enumDepthFormatTypeData.hh>

#include <string>
#include <iostream>
#include <locale>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace DomainVision {
	
	class DepthFormatType {
	private:
		DomainVisionIDL::DepthFormatType value;
		
	public:
		enum ENUM_DepthFormatType {
			ENUM_VALUE_UNDEFINED = 0,
			UINT8 = 1,
			UINT16 = 2,
			FLOAT = 3,
			DOUBLE = 4
		};
		
		// default constructor
		DepthFormatType() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		DepthFormatType(ENUM_DepthFormatType e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type (which is typically int)
		DepthFormatType(DomainVisionIDL::DepthFormatType e) {
			value = e;
		}
		
		//const DomainVisionIDL::DepthFormatType& get() const { return value; }
		
		// ENUM operator
		operator ENUM_DepthFormatType() const {
			return static_cast<ENUM_DepthFormatType>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_DepthFormatType t) const {
			return this->value == t;
		}
		
		std::string to_string(const bool &use_fqn=true) const {
			std::string result = "";
			if(use_fqn == true) {
				result = "DepthFormatType::";
			}
			switch (value) {
				case UINT8:
					result += "UINT8";
					break;
				case UINT16:
					result += "UINT16";
					break;
				case FLOAT:
					result += "FLOAT";
					break;
				case DOUBLE:
					result += "DOUBLE";
					break;
				default:
					result += "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		static DepthFormatType from_string(const std::string &value) {
			std::string input = value;
			std::locale l;
			for(auto &c: input) {
				// convert all characters to lower case (so string comparison works regardless of small/capital letters)
				c = std::tolower(c,l);
			}
			std::string base_name = "depthformattype::";
			if(input.compare(0, base_name.length(), base_name) == 0) {
				// remove basename from comparing the actual enumeration
				input.erase(0,base_name.length());
			}
			if(input == "uint8"){
				return DepthFormatType(UINT8);
			}
			if(input == "uint16"){
				return DepthFormatType(UINT16);
			}
			if(input == "float"){
				return DepthFormatType(FLOAT);
			}
			if(input == "double"){
				return DepthFormatType(DOUBLE);
			}
			// default (if none of the preceding options match)
			return DepthFormatType();
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const DepthFormatType &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
