//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINVISION_FORMATTYPE_ENUM_H_
#define DOMAINVISION_FORMATTYPE_ENUM_H_

#include <DomainVision/enumFormatTypeData.hh>

#include <string>
#include <iostream>
#include <locale>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace DomainVision {
	
	class FormatType {
	private:
		DomainVisionIDL::FormatType value;
		
	public:
		enum ENUM_FormatType {
			ENUM_VALUE_UNDEFINED = 0,
			GREY = 1,
			RGB565 = 2,
			RGB555 = 3,
			RGB24 = 4,
			RGB32 = 5,
			YUV422 = 6,
			YUYV = 7,
			UYVY = 8,
			YUV420P = 9,
			YUV422P = 10,
			YUV411P = 11
		};
		
		// default constructor
		FormatType() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		FormatType(ENUM_FormatType e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type (which is typically int)
		FormatType(DomainVisionIDL::FormatType e) {
			value = e;
		}
		
		//const DomainVisionIDL::FormatType& get() const { return value; }
		
		// ENUM operator
		operator ENUM_FormatType() const {
			return static_cast<ENUM_FormatType>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_FormatType t) const {
			return this->value == t;
		}
		
		std::string to_string(const bool &use_fqn=true) const {
			std::string result = "";
			if(use_fqn == true) {
				result = "FormatType::";
			}
			switch (value) {
				case GREY:
					result += "GREY";
					break;
				case RGB565:
					result += "RGB565";
					break;
				case RGB555:
					result += "RGB555";
					break;
				case RGB24:
					result += "RGB24";
					break;
				case RGB32:
					result += "RGB32";
					break;
				case YUV422:
					result += "YUV422";
					break;
				case YUYV:
					result += "YUYV";
					break;
				case UYVY:
					result += "UYVY";
					break;
				case YUV420P:
					result += "YUV420P";
					break;
				case YUV422P:
					result += "YUV422P";
					break;
				case YUV411P:
					result += "YUV411P";
					break;
				default:
					result += "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		static FormatType from_string(const std::string &value) {
			std::string input = value;
			std::locale l;
			for(auto &c: input) {
				// convert all characters to lower case (so string comparison works regardless of small/capital letters)
				c = std::tolower(c,l);
			}
			std::string base_name = "formattype::";
			if(input.compare(0, base_name.length(), base_name) == 0) {
				// remove basename from comparing the actual enumeration
				input.erase(0,base_name.length());
			}
			if(input == "grey"){
				return FormatType(GREY);
			}
			if(input == "rgb565"){
				return FormatType(RGB565);
			}
			if(input == "rgb555"){
				return FormatType(RGB555);
			}
			if(input == "rgb24"){
				return FormatType(RGB24);
			}
			if(input == "rgb32"){
				return FormatType(RGB32);
			}
			if(input == "yuv422"){
				return FormatType(YUV422);
			}
			if(input == "yuyv"){
				return FormatType(YUYV);
			}
			if(input == "uyvy"){
				return FormatType(UYVY);
			}
			if(input == "yuv420p"){
				return FormatType(YUV420P);
			}
			if(input == "yuv422p"){
				return FormatType(YUV422P);
			}
			if(input == "yuv411p"){
				return FormatType(YUV411P);
			}
			// default (if none of the preceding options match)
			return FormatType();
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const FormatType &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
