//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#ifndef COMMMANIPULATORREQUESTSCAN3D_JSON_TRANSFORMATION_H_
#define COMMMANIPULATORREQUESTSCAN3D_JSON_TRANSFORMATION_H_

#include <nlohmann/json.hpp>

#include <CommManipulatorObjects/CommManipulatorRequestScan3dData.hh>

namespace CommManipulatorObjectsIDL {

	void to_json(const CommManipulatorObjectsIDL::CommManipulatorRequestScan3d& obj, nlohmann::json& j);
	void from_json(const nlohmann::json& j, CommManipulatorObjectsIDL::CommManipulatorRequestScan3d& obj);
	
} // end namespace CommManipulatorObjectsIDL

#endif // COMMMANIPULATORREQUESTSCAN3D_JSON_TRANSFORMATION_H_
