//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommGraspJSON.hh"

#include "CommBasicObjectsJSON/CommPose3dJSON.hh"

namespace CommManipulatorObjectsIDL {

void to_json(const CommManipulatorObjectsIDL::CommGrasp& obj, nlohmann::json& j)
{
	// id: String
	j["id"] = obj.id;
	// pose: CommPose3d
	to_json(obj.pose, j["pose"]);
	// quality: Double
	j["quality"] = obj.quality;
	// width: Double
	j["width"] = obj.width;
	// valid: Boolean
	j["valid"] = obj.valid;
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, CommManipulatorObjectsIDL::CommGrasp& obj)
{
	// id: String
	if(j.contains("id") && j["id"].is_string()) {
		obj.id = j["id"].get<std::string>();
	}
	// pose: CommPose3d
	if(j.contains("pose") && j["pose"].is_object()) {
		//from_json(j["pose"], obj.pose);
		obj.pose = j["pose"].get<CommBasicObjectsIDL::CommPose3d>();
	}
	// quality: Double
	if(j.contains("quality") && j["quality"].is_number_float()) {
		obj.quality = j["quality"].get<double>();
	}
	// width: Double
	if(j.contains("width") && j["width"].is_number_float()) {
		obj.width = j["width"].get<double>();
	}
	// valid: Boolean
	if(j.contains("valid") && j["valid"].is_boolean()) {
		obj.valid = j["valid"].get<bool>();
	}
}

} // end namespace CommManipulatorObjectsIDL
