//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#ifndef COMMPTUSTATE_JSON_TRANSFORMATION_H_
#define COMMPTUSTATE_JSON_TRANSFORMATION_H_

#include <nlohmann/json.hpp>

#include <DomainPTU/CommPTUStateData.hh>

namespace DomainPTUIDL {

	void to_json(const DomainPTUIDL::CommPTUState& obj, nlohmann::json& j);
	void from_json(const nlohmann::json& j, DomainPTUIDL::CommPTUState& obj);
	
} // end namespace DomainPTUIDL

#endif // COMMPTUSTATE_JSON_TRANSFORMATION_H_
