//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#ifndef COMMMOBILEPTUSTATE_JSON_TRANSFORMATION_H_
#define COMMMOBILEPTUSTATE_JSON_TRANSFORMATION_H_

#include <nlohmann/json.hpp>

#include <DomainPTU/CommMobilePTUStateData.hh>

namespace DomainPTUIDL {

	void to_json(const DomainPTUIDL::CommMobilePTUState& obj, nlohmann::json& j);
	void from_json(const nlohmann::json& j, DomainPTUIDL::CommMobilePTUState& obj);
	
} // end namespace DomainPTUIDL

#endif // COMMMOBILEPTUSTATE_JSON_TRANSFORMATION_H_
