//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommPTUGoalEventParameterJSON.hh"

#include <DomainPTU/enumPTUMoveStatus.hh>

namespace DomainPTUIDL {

void to_json(const DomainPTUIDL::CommPTUGoalEventParameter& obj, nlohmann::json& j)
{
	// oldState: PTUMoveStatus
	j["oldState"] = DomainPTU::PTUMoveStatus(obj.oldState).to_string(false);
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, DomainPTUIDL::CommPTUGoalEventParameter& obj)
{
	// oldState: PTUMoveStatus
	if(j.contains("oldState") && j["oldState"].is_string()) {
		obj.oldState = DomainPTU::PTUMoveStatus::from_string(j["oldState"].get<std::string>());
	}
}

} // end namespace DomainPTUIDL
