//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommPTUMoveResponseJSON.hh"

#include "CommBasicObjectsJSON/CommPose3dJSON.hh"
#include "CommBasicObjectsJSON/CommBaseStateJSON.hh"

namespace DomainPTUIDL {

void to_json(const DomainPTUIDL::CommPTUMoveResponse& obj, nlohmann::json& j)
{
	// devicePose: CommPose3d
	to_json(obj.devicePose, j["devicePose"]);
	// stateBase: CommBaseState
	to_json(obj.stateBase, j["stateBase"]);
	// status: PTUMoveStatus
	j["status"] = obj.status;
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, DomainPTUIDL::CommPTUMoveResponse& obj)
{
	// devicePose: CommPose3d
	if(j.contains("devicePose") && j["devicePose"].is_object()) {
		//from_json(j["devicePose"], obj.devicePose);
		obj.devicePose = j["devicePose"].get<CommBasicObjectsIDL::CommPose3d>();
	}
	// stateBase: CommBaseState
	if(j.contains("stateBase") && j["stateBase"].is_object()) {
		//from_json(j["stateBase"], obj.stateBase);
		obj.stateBase = j["stateBase"].get<CommBasicObjectsIDL::CommBaseState>();
	}
	// status: PTUMoveStatus
	if(j.contains("status") && j["status"].is_number_integer()) {
		obj.status = j["status"].get<int>();
	}
}

} // end namespace DomainPTUIDL
