//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommManipulationPlannerEventParameterJSON.hh"

#include <CommManipulationPlannerObjects/enumManipulationPlannerEvent.hh>

namespace CommManipulationPlannerObjectsIDL {

void to_json(const CommManipulationPlannerObjectsIDL::CommManipulationPlannerEventParameter& obj, nlohmann::json& j)
{
	// event: ManipulationPlannerEvent
	j["event"] = CommManipulationPlannerObjects::ManipulationPlannerEvent(obj.event).to_string(false);
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, CommManipulationPlannerObjectsIDL::CommManipulationPlannerEventParameter& obj)
{
	// event: ManipulationPlannerEvent
	if(j.contains("event") && j["event"].is_string()) {
		obj.event = CommManipulationPlannerObjects::ManipulationPlannerEvent::from_string(j["event"].get<std::string>());
	}
}

} // end namespace CommManipulationPlannerObjectsIDL
