//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainRobotFleetNavigation/CommNodeStatusUpdateRequestCore.hh"

// serialization/deserialization operators
//#include "DomainRobotFleetNavigation/CommNodeStatusUpdateRequestACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace DomainRobotFleetNavigation 
{
	const char* CommNodeStatusUpdateRequestCore::getCompiledHash()
	{
		return DomainRobotFleetNavigationIDL::REPO_HASH;
	}
	
	void CommNodeStatusUpdateRequestCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
	}
	
	void CommNodeStatusUpdateRequestCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommNodeStatusUpdateRequestCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
	}
	
	#ifdef ENABLE_HASH
	size_t CommNodeStatusUpdateRequestCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		boost::hash_combine(seed, data.id);
		boost::hash_combine(seed, data.type);
		
		return seed;
	}
	#endif
	
	// default constructor
	CommNodeStatusUpdateRequestCore::CommNodeStatusUpdateRequestCore()
	:	idl_CommNodeStatusUpdateRequest()
	{  
		setId(0);
		setType(DomainRobotFleetNavigation::StatusUpdateType());
	}
	
	CommNodeStatusUpdateRequestCore::CommNodeStatusUpdateRequestCore(const DATATYPE &data)
	:	idl_CommNodeStatusUpdateRequest(data)
	{  }

	CommNodeStatusUpdateRequestCore::~CommNodeStatusUpdateRequestCore()
	{  }
	
	void CommNodeStatusUpdateRequestCore::to_ostream(std::ostream &os) const
	{
	  os << "CommNodeStatusUpdateRequest(";
	  os << getId() << " ";
	  getType().to_ostream(os);
	  os << ") ";
	}
	
	// convert to xml stream
	void CommNodeStatusUpdateRequestCore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<id>" << getId() << "</id>";
		os << indent << "<type>";
		getType().to_xml(os, indent);
		os << indent << "</type>";
	}
	
	// restore from xml stream
	void CommNodeStatusUpdateRequestCore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_id("<id>");
		static const Smart::KnuthMorrisPratt kmp_type("<type>");
		
		if(kmp_id.search(is)) {
			int idItem;
			is >> idItem;
			setId(idItem);
		}
		if(kmp_type.search(is)) {
			DomainRobotFleetNavigation::StatusUpdateType typeItem;
			typeItem.from_xml(is);
			setType(typeItem);
		}
	}
	
	/*
	void CommNodeStatusUpdateRequestCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		DomainRobotFleetNavigationIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(DomainRobotFleetNavigationIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommNodeStatusUpdateRequestACE.hh)
		cdr << idl_CommNodeStatusUpdateRequest;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommNodeStatusUpdateRequest);
		cdr << data_hash;
		// std::cout << "CommNodeStatusUpdateRequestCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommNodeStatusUpdateRequestCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		DomainRobotFleetNavigationIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommNodeStatusUpdateRequestACE.hh)
		cdr >> idl_CommNodeStatusUpdateRequest;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommNodeStatusUpdateRequest);
		assert(data_hash == own_hash);
		// std::cout << "CommNodeStatusUpdateRequestCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace DomainRobotFleetNavigation */
