//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINROBOTFLEETNAVIGATION_STATUSUPDATETYPE_ENUM_H_
#define DOMAINROBOTFLEETNAVIGATION_STATUSUPDATETYPE_ENUM_H_

#include <DomainRobotFleetNavigation/enumStatusUpdateTypeData.hh>

#include <string>
#include <iostream>
#include <locale>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace DomainRobotFleetNavigation {
	
	class StatusUpdateType {
	private:
		DomainRobotFleetNavigationIDL::StatusUpdateType value;
		
	public:
		enum ENUM_StatusUpdateType {
			ENUM_VALUE_UNDEFINED = 0,
			FREENODE = 1,
			ACQUIRENODE = 2
		};
		
		// default constructor
		StatusUpdateType() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		StatusUpdateType(ENUM_StatusUpdateType e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type (which is typically int)
		StatusUpdateType(DomainRobotFleetNavigationIDL::StatusUpdateType e) {
			value = e;
		}
		
		//const DomainRobotFleetNavigationIDL::StatusUpdateType& get() const { return value; }
		
		// ENUM operator
		operator ENUM_StatusUpdateType() const {
			return static_cast<ENUM_StatusUpdateType>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_StatusUpdateType t) const {
			return this->value == t;
		}
		
		std::string to_string(const bool &use_fqn=true) const {
			std::string result = "";
			if(use_fqn == true) {
				result = "StatusUpdateType::";
			}
			switch (value) {
				case FREENODE:
					result += "FREENODE";
					break;
				case ACQUIRENODE:
					result += "ACQUIRENODE";
					break;
				default:
					result += "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		static StatusUpdateType from_string(const std::string &value) {
			std::string input = value;
			std::locale l;
			for(auto &c: input) {
				// convert all characters to lower case (so string comparison works regardless of small/capital letters)
				c = std::tolower(c,l);
			}
			std::string base_name = "statusupdatetype::";
			if(input.compare(0, base_name.length(), base_name) == 0) {
				// remove basename from comparing the actual enumeration
				input.erase(0,base_name.length());
			}
			if(input == "freenode"){
				return StatusUpdateType(FREENODE);
			}
			if(input == "acquirenode"){
				return StatusUpdateType(ACQUIRENODE);
			}
			// default (if none of the preceding options match)
			return StatusUpdateType();
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const StatusUpdateType &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
