//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINEXTERNALSYSTEMS_COMMEXTERNALPROGRAMARGUMENT_ACE_H_
#define DOMAINEXTERNALSYSTEMS_COMMEXTERNALPROGRAMARGUMENT_ACE_H_

#include "DomainExternalSystems/CommExternalProgramArgument.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure CommExternalProgramArgument
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainExternalSystemsIDL::CommExternalProgramArgument &data);

// de-serialization operator for DataStructure CommExternalProgramArgument
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainExternalSystemsIDL::CommExternalProgramArgument &data);

// serialization operator for CommunicationObject CommExternalProgramArgument
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainExternalSystems::CommExternalProgramArgument &obj);

// de-serialization operator for CommunicationObject CommExternalProgramArgument
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainExternalSystems::CommExternalProgramArgument &obj);

#endif /* DOMAINEXTERNALSYSTEMS_COMMEXTERNALPROGRAMARGUMENT_ACE_H_ */
