//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainExternalSystems/CommExternalProgramResponseACE.hh"
#include <ace/SString.h>
#include "DomainExternalSystems/enumExternalProgramStatusData.hh"
#include "DomainExternalSystems/CommExternalProgramArgumentACE.hh"
#include "DomainExternalSystems/enumExternalProgramResultData.hh"

// serialization operator for element CommExternalProgramResponse
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainExternalSystemsIDL::CommExternalProgramResponse &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element status
	good_bit = good_bit && cdr.write_long(data.status);
	// serialize list-element result
	good_bit = good_bit && cdr.write_long(data.result);
	// serialize list-element resultArgs
	good_bit = good_bit && cdr << ACE_Utils::truncate_cast<ACE_CDR::ULong>(data.resultArgs.size());
	std::vector<DomainExternalSystemsIDL::CommExternalProgramArgument>::const_iterator data_resultArgsIt;
	for(data_resultArgsIt=data.resultArgs.begin(); data_resultArgsIt!=data.resultArgs.end(); data_resultArgsIt++) {
		good_bit = good_bit && cdr << *data_resultArgsIt;
	}
	
	return good_bit;
}

// de-serialization operator for element CommExternalProgramResponse
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainExternalSystemsIDL::CommExternalProgramResponse &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element status
	good_bit = good_bit && cdr.read_long(data.status);
	// deserialize type element result
	good_bit = good_bit && cdr.read_long(data.result);
	// deserialize list-type element resultArgs
	ACE_CDR::ULong data_resultArgsNbr;
	good_bit = good_bit && cdr >> data_resultArgsNbr;
	data.resultArgs.clear();
	DomainExternalSystemsIDL::CommExternalProgramArgument data_resultArgsItem;
	for(ACE_CDR::ULong i=0; i<data_resultArgsNbr; ++i) {
		good_bit = good_bit && cdr >> data_resultArgsItem;
		data.resultArgs.push_back(data_resultArgsItem);
	}
	
	return good_bit;
}

// serialization operator for CommunicationObject CommExternalProgramResponse
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainExternalSystems::CommExternalProgramResponse &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommExternalProgramResponse
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainExternalSystems::CommExternalProgramResponse &obj)
{
	return cdr >> obj.set();
}
