//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#ifndef COMMSTEREOIMAGE_JSON_TRANSFORMATION_H_
#define COMMSTEREOIMAGE_JSON_TRANSFORMATION_H_

#include <nlohmann/json.hpp>

#include <DomainVision/CommStereoImageData.hh>

namespace DomainVisionIDL {

	void to_json(const DomainVisionIDL::CommStereoImage& obj, nlohmann::json& j);
	void from_json(const nlohmann::json& j, DomainVisionIDL::CommStereoImage& obj);
	
} // end namespace DomainVisionIDL

#endif // COMMSTEREOIMAGE_JSON_TRANSFORMATION_H_
