//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#ifndef COMMEXTERNALPROGRAMARGUMENT_JSON_TRANSFORMATION_H_
#define COMMEXTERNALPROGRAMARGUMENT_JSON_TRANSFORMATION_H_

#include <nlohmann/json.hpp>

#include <DomainExternalSystems/CommExternalProgramArgumentData.hh>

namespace DomainExternalSystemsIDL {

	void to_json(const DomainExternalSystemsIDL::CommExternalProgramArgument& obj, nlohmann::json& j);
	void from_json(const nlohmann::json& j, DomainExternalSystemsIDL::CommExternalProgramArgument& obj);
	
} // end namespace DomainExternalSystemsIDL

#endif // COMMEXTERNALPROGRAMARGUMENT_JSON_TRANSFORMATION_H_
