//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommExternalProgamEventParamJSON.hh"

#include <DomainExternalSystems/enumExternalProgramStatus.hh>

namespace DomainExternalSystemsIDL {

void to_json(const DomainExternalSystemsIDL::CommExternalProgamEventParam& obj, nlohmann::json& j)
{
	// status: ExternalProgramStatus
	j["status"] = DomainExternalSystems::ExternalProgramStatus(obj.status).to_string(false);
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, DomainExternalSystemsIDL::CommExternalProgamEventParam& obj)
{
	// status: ExternalProgramStatus
	if(j.contains("status") && j["status"].is_string()) {
		obj.status = DomainExternalSystems::ExternalProgramStatus::from_string(j["status"].get<std::string>());
	}
}

} // end namespace DomainExternalSystemsIDL
