//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommCdlRobotBlockedEventParameterJSON.hh"

#include <CommNavigationObjects/enumCdlRobotBlockEventType.hh>

namespace CommNavigationObjectsIDL {

void to_json(const CommNavigationObjectsIDL::CommCdlRobotBlockedEventParameter& obj, nlohmann::json& j)
{
	// oldState: CdlRobotBlockEventType
	j["oldState"] = CommNavigationObjects::CdlRobotBlockEventType(obj.oldState).to_string(false);
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, CommNavigationObjectsIDL::CommCdlRobotBlockedEventParameter& obj)
{
	// oldState: CdlRobotBlockEventType
	if(j.contains("oldState") && j["oldState"].is_string()) {
		obj.oldState = CommNavigationObjects::CdlRobotBlockEventType::from_string(j["oldState"].get<std::string>());
	}
}

} // end namespace CommNavigationObjectsIDL
