//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommBundledNavigationEventStateJSON.hh"

#include <CommNavigationObjects/enumBundledNavigationGoalState.hh>

namespace CommNavigationObjectsIDL {

void to_json(const CommNavigationObjectsIDL::CommBundledNavigationEventState& obj, nlohmann::json& j)
{
	// locationName: String
	j["locationName"] = obj.locationName;
	// goalState: BundledNavigationGoalState
	j["goalState"] = CommNavigationObjects::BundledNavigationGoalState(obj.goalState).to_string(false);
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, CommNavigationObjectsIDL::CommBundledNavigationEventState& obj)
{
	// locationName: String
	if(j.contains("locationName") && j["locationName"].is_string()) {
		obj.locationName = j["locationName"].get<std::string>();
	}
	// goalState: BundledNavigationGoalState
	if(j.contains("goalState") && j["goalState"].is_string()) {
		obj.goalState = CommNavigationObjects::BundledNavigationGoalState::from_string(j["goalState"].get<std::string>());
	}
}

} // end namespace CommNavigationObjectsIDL
