//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommSymbolicPlannerRequestJSON.hh"


namespace DomainSymbolicPlannerIDL {

void to_json(const DomainSymbolicPlannerIDL::CommSymbolicPlannerRequest& obj, nlohmann::json& j)
{
	// plannertype: String
	j["plannertype"] = obj.plannertype;
	// domaindescription: String
	j["domaindescription"] = obj.domaindescription;
	// factdescription: String
	j["factdescription"] = obj.factdescription;
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, DomainSymbolicPlannerIDL::CommSymbolicPlannerRequest& obj)
{
	// plannertype: String
	if(j.contains("plannertype") && j["plannertype"].is_string()) {
		obj.plannertype = j["plannertype"].get<std::string>();
	}
	// domaindescription: String
	if(j.contains("domaindescription") && j["domaindescription"].is_string()) {
		obj.domaindescription = j["domaindescription"].get<std::string>();
	}
	// factdescription: String
	if(j.contains("factdescription") && j["factdescription"].is_string()) {
		obj.factdescription = j["factdescription"].get<std::string>();
	}
}

} // end namespace DomainSymbolicPlannerIDL
