//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMOBJECTRECOGNITIONOBJECTS_COMMIMAGEOBJECTRECOGNITIONRESULT_DATA_H_
#define COMMOBJECTRECOGNITIONOBJECTS_COMMIMAGEOBJECTRECOGNITIONRESULT_DATA_H_

#include "CommObjectRecognitionObjects/CommObjectBeliefData.hh"


namespace CommObjectRecognitionObjectsIDL 
{
	struct CommImageObjectRecognitionResult
	{
		unsigned int xmin;
		unsigned int ymin;
		unsigned int xmax;
		unsigned int ymax;
		CommObjectRecognitionObjectsIDL::CommObjectBelief belief;
		unsigned int objectId;
  	};
};

#endif /* COMMOBJECTRECOGNITIONOBJECTS_COMMIMAGEOBJECTRECOGNITIONRESULT_DATA_H_ */
