//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommObjectRecognitionObjects/CommImageObjectRecognitionResultsCore.hh"

// serialization/deserialization operators
//#include "CommObjectRecognitionObjects/CommImageObjectRecognitionResultsACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace CommObjectRecognitionObjects 
{
	const char* CommImageObjectRecognitionResultsCore::getCompiledHash()
	{
		return CommObjectRecognitionObjectsIDL::REPO_HASH;
	}
	
	void CommImageObjectRecognitionResultsCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
		// get hash value(s) for CommObjectRecognitionObjects::CommImageObjectRecognitionResult(idl_CommImageObjectRecognitionResults.objects)
		CommObjectRecognitionObjects::CommImageObjectRecognitionResult::getAllHashValues(hashes);
		// get hash value(s) for CommBasicObjects::CommTimeStamp(idl_CommImageObjectRecognitionResults.timestamp)
		CommBasicObjects::CommTimeStamp::getAllHashValues(hashes);
	}
	
	void CommImageObjectRecognitionResultsCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommImageObjectRecognitionResultsCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
		// check hash value(s) for CommObjectRecognitionObjects::CommImageObjectRecognitionResult(idl_CommImageObjectRecognitionResults.objects)
		CommObjectRecognitionObjects::CommImageObjectRecognitionResult::checkAllHashValues(hashes);
		// check hash value(s) for CommBasicObjects::CommTimeStamp(idl_CommImageObjectRecognitionResults.timestamp)
		CommBasicObjects::CommTimeStamp::checkAllHashValues(hashes);
	}
	
	#ifdef ENABLE_HASH
	size_t CommImageObjectRecognitionResultsCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		std::vector<CommObjectRecognitionObjectsIDL::CommImageObjectRecognitionResult>::const_iterator data_objectsIt;
		for(data_objectsIt=data.objects.begin(); data_objectsIt!=data.objects.end(); data_objectsIt++) {
			seed += CommObjectRecognitionObjects::CommImageObjectRecognitionResult::generateDataHash(*data_objectsIt);
		}
		seed += CommBasicObjects::CommTimeStamp::generateDataHash(data.timestamp);
		boost::hash_combine(seed, data.environmentId);
		boost::hash_combine(seed, data.valid);
		
		return seed;
	}
	#endif
	
	// default constructor
	CommImageObjectRecognitionResultsCore::CommImageObjectRecognitionResultsCore()
	:	idl_CommImageObjectRecognitionResults()
	{  
		setObjects(std::vector<CommObjectRecognitionObjects::CommImageObjectRecognitionResult>());
		setTimestamp(CommBasicObjects::CommTimeStamp());
		setEnvironmentId(0);
		setValid(false);
	}
	
	CommImageObjectRecognitionResultsCore::CommImageObjectRecognitionResultsCore(const DATATYPE &data)
	:	idl_CommImageObjectRecognitionResults(data)
	{  }

	CommImageObjectRecognitionResultsCore::~CommImageObjectRecognitionResultsCore()
	{  }
	
	void CommImageObjectRecognitionResultsCore::to_ostream(std::ostream &os) const
	{
	  os << "CommImageObjectRecognitionResults(";
	  std::vector<CommObjectRecognitionObjects::CommImageObjectRecognitionResult>::const_iterator objectsIt;
	  std::vector<CommObjectRecognitionObjects::CommImageObjectRecognitionResult> objectsList = getObjectsCopy();
	  for(objectsIt=objectsList.begin(); objectsIt!=objectsList.end(); objectsIt++) {
	  	objectsIt->to_ostream(os);
	  }
	  getTimestamp().to_ostream(os);
	  os << getEnvironmentId() << " ";
	  os << getValid() << " ";
	  os << ") ";
	}
	
	// convert to xml stream
	void CommImageObjectRecognitionResultsCore::to_xml(std::ostream &os, const std::string &indent) const {
		size_t counter = 0;
		
		std::vector<CommObjectRecognitionObjects::CommImageObjectRecognitionResult>::const_iterator objectsIt;
		std::vector<CommObjectRecognitionObjects::CommImageObjectRecognitionResult> objectsList = getObjectsCopy();
		counter = 0;
		os << indent << "<objectsList n=\"" << objectsList.size() << "\">";
		for(objectsIt=objectsList.begin(); objectsIt!=objectsList.end(); objectsIt++) {
			os << indent << "<objects i=\"" << counter++ << "\">";
			objectsIt->to_xml(os, indent);
			os << indent << "</objects>";
		}
		os << indent << "</objectsList>";
		os << indent << "<timestamp>";
		getTimestamp().to_xml(os, indent);
		os << indent << "</timestamp>";
		os << indent << "<environmentId>" << getEnvironmentId() << "</environmentId>";
		os << indent << "<valid>" << getValid() << "</valid>";
	}
	
	// restore from xml stream
	void CommImageObjectRecognitionResultsCore::from_xml(std::istream &is) {
		size_t counter = 0;
		
		static const Smart::KnuthMorrisPratt kmp_objectsList("<objectsList n=\"");
		static const Smart::KnuthMorrisPratt kmp_objects("\">");
		static const Smart::KnuthMorrisPratt kmp_timestamp("<timestamp>");
		static const Smart::KnuthMorrisPratt kmp_environmentId("<environmentId>");
		static const Smart::KnuthMorrisPratt kmp_valid("<valid>");
		
		if(kmp_objectsList.search(is)) {
			size_t numberElements;
			is >> numberElements;
			CommObjectRecognitionObjects::CommImageObjectRecognitionResult objectsItem;
			std::vector<CommObjectRecognitionObjects::CommImageObjectRecognitionResult> objectsList;
			kmp_objects.search(is);
			for(counter=0; counter<numberElements; counter++) {
				if(kmp_objects.search(is)) {
					objectsItem.from_xml(is);
					objectsList.push_back(objectsItem);
				}
			}
			setObjects(objectsList);
		}
		if(kmp_timestamp.search(is)) {
			CommBasicObjects::CommTimeStamp timestampItem;
			timestampItem.from_xml(is);
			setTimestamp(timestampItem);
		}
		if(kmp_environmentId.search(is)) {
			unsigned int environmentIdItem;
			is >> environmentIdItem;
			setEnvironmentId(environmentIdItem);
		}
		if(kmp_valid.search(is)) {
			bool validItem;
			is >> validItem;
			setValid(validItem);
		}
	}
	
	/*
	void CommImageObjectRecognitionResultsCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		CommObjectRecognitionObjectsIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(CommObjectRecognitionObjectsIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommImageObjectRecognitionResultsACE.hh)
		cdr << idl_CommImageObjectRecognitionResults;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommImageObjectRecognitionResults);
		cdr << data_hash;
		// std::cout << "CommImageObjectRecognitionResultsCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommImageObjectRecognitionResultsCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		CommObjectRecognitionObjectsIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommImageObjectRecognitionResultsACE.hh)
		cdr >> idl_CommImageObjectRecognitionResults;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommImageObjectRecognitionResults);
		assert(data_hash == own_hash);
		// std::cout << "CommImageObjectRecognitionResultsCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace CommObjectRecognitionObjects */
