//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMOBJECTRECOGNITIONOBJECTS_COMMIMAGEOBJECTRECOGNITIONRESULTS_ACE_H_
#define COMMOBJECTRECOGNITIONOBJECTS_COMMIMAGEOBJECTRECOGNITIONRESULTS_ACE_H_

#include "CommObjectRecognitionObjects/CommImageObjectRecognitionResults.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure CommImageObjectRecognitionResults
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommObjectRecognitionObjectsIDL::CommImageObjectRecognitionResults &data);

// de-serialization operator for DataStructure CommImageObjectRecognitionResults
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommObjectRecognitionObjectsIDL::CommImageObjectRecognitionResults &data);

// serialization operator for CommunicationObject CommImageObjectRecognitionResults
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommObjectRecognitionObjects::CommImageObjectRecognitionResults &obj);

// de-serialization operator for CommunicationObject CommImageObjectRecognitionResults
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommObjectRecognitionObjects::CommImageObjectRecognitionResults &obj);

#endif /* COMMOBJECTRECOGNITIONOBJECTS_COMMIMAGEOBJECTRECOGNITIONRESULTS_ACE_H_ */
