//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMOBJECTRECOGNITIONOBJECTS_MANIPULATIONDUMMY_CORE_H_
#define COMMOBJECTRECOGNITIONOBJECTS_MANIPULATIONDUMMY_CORE_H_

#include "CommObjectRecognitionObjects/ManipulationDummyData.hh"
#include "CommManipulatorObjects/CommMobileManipulatorState.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommObjectRecognitionObjects {
	
class ManipulationDummyCore {
protected:
	// data structure
	CommObjectRecognitionObjectsIDL::ManipulationDummy idl_ManipulationDummy;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommObjectRecognitionObjectsIDL::ManipulationDummy DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	ManipulationDummyCore();
	ManipulationDummyCore(const DATATYPE &data);
	// default destructor
	virtual ~ManipulationDummyCore();
	
	const DATATYPE& get() const { return idl_ManipulationDummy; }
	operator const DATATYPE&() const { return idl_ManipulationDummy; }
	DATATYPE& set() { return idl_ManipulationDummy; }

	static inline std::string identifier(void) { return "CommObjectRecognitionObjects::ManipulationDummy"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Value
	inline CommManipulatorObjects::CommMobileManipulatorState getValue() const { return CommManipulatorObjects::CommMobileManipulatorState(idl_ManipulationDummy.value); }
	inline ManipulationDummyCore& setValue(const CommManipulatorObjects::CommMobileManipulatorState &value) { idl_ManipulationDummy.value = value; return *this; }
};

} /* namespace CommObjectRecognitionObjects */
#endif /* COMMOBJECTRECOGNITIONOBJECTS_MANIPULATIONDUMMY_CORE_H_ */
