//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommNavPathJSON.hh"

#include "DomainRobotFleetNavigationJSON/CommPathJSON.hh"

namespace DomainRobotFleetNavigationIDL {

void to_json(const DomainRobotFleetNavigationIDL::CommNavPath& obj, nlohmann::json& j)
{
	// path: CommPath[]
	for(size_t idx=0; idx < obj.path.size(); idx++) {
		nlohmann::json array_element;
		to_json(obj.path.at(idx), array_element);
		j["path"].emplace_back(array_element);
	}
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, DomainRobotFleetNavigationIDL::CommNavPath& obj)
{
	// path: CommPath[]
	if(j.contains("path") && j["path"].is_array()) {
		auto jpath = j["path"];
		obj.path.resize(jpath.size());
		for(size_t idx=0; idx < jpath.size(); idx++) {
			// convert the json array values individually
			if(jpath.at(idx).is_object()) {
				// from_json(jpath.at(idx), obj.path.at(idx));
				obj.path[idx] = jpath[idx].get<DomainRobotFleetNavigationIDL::CommPath>();
			}
		}
	}
}

} // end namespace DomainRobotFleetNavigationIDL
