//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommNodeStatusUpdateAnswerJSON.hh"


namespace DomainRobotFleetNavigationIDL {

void to_json(const DomainRobotFleetNavigationIDL::CommNodeStatusUpdateAnswer& obj, nlohmann::json& j)
{
	// success: Boolean
	j["success"] = obj.success;
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, DomainRobotFleetNavigationIDL::CommNodeStatusUpdateAnswer& obj)
{
	// success: Boolean
	if(j.contains("success") && j["success"].is_boolean()) {
		obj.success = j["success"].get<bool>();
	}
}

} // end namespace DomainRobotFleetNavigationIDL
