//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMMANIPULATOROBJECTS_COMMVACUUMGRIPPEREVENTPARAMETER_H_
#define COMMMANIPULATOROBJECTS_COMMVACUUMGRIPPEREVENTPARAMETER_H_

#include "CommManipulatorObjects/CommVacuumGripperEventParameterCore.hh"

namespace CommManipulatorObjects {
		
class CommVacuumGripperEventParameter : public CommVacuumGripperEventParameterCore {
	public:
		// default constructors
		CommVacuumGripperEventParameter();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommVacuumGripperEventParameter(const CommManipulatorObjects::VacuumGraspState &state);
		
		CommVacuumGripperEventParameter(const CommVacuumGripperEventParameterCore &commVacuumGripperEventParameter);
		CommVacuumGripperEventParameter(const DATATYPE &commVacuumGripperEventParameter);
		virtual ~CommVacuumGripperEventParameter();
		
		// use framework specific getter and setter methods from core (base) class
		using CommVacuumGripperEventParameterCore::get;
		using CommVacuumGripperEventParameterCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommVacuumGripperEventParameter &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommManipulatorObjects */
#endif /* COMMMANIPULATOROBJECTS_COMMVACUUMGRIPPEREVENTPARAMETER_H_ */
