//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMMANIPULATOROBJECTS_COMMINVERSEKINEMATICSREQUEST_H_
#define COMMMANIPULATOROBJECTS_COMMINVERSEKINEMATICSREQUEST_H_

#include "CommManipulatorObjects/CommInverseKinematicsRequestCore.hh"

namespace CommManipulatorObjects {
		
class CommInverseKinematicsRequest : public CommInverseKinematicsRequestCore {
	public:
		// default constructors
		CommInverseKinematicsRequest();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommInverseKinematicsRequest(const CommBasicObjects::CommPose3d &tcp_pose, const unsigned char &motion_constraints, const bool &is_relative = false);
		
		CommInverseKinematicsRequest(const CommInverseKinematicsRequestCore &commInverseKinematicsRequest);
		CommInverseKinematicsRequest(const DATATYPE &commInverseKinematicsRequest);
		virtual ~CommInverseKinematicsRequest();
		
		// use framework specific getter and setter methods from core (base) class
		using CommInverseKinematicsRequestCore::get;
		using CommInverseKinematicsRequestCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommInverseKinematicsRequest &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommManipulatorObjects */
#endif /* COMMMANIPULATOROBJECTS_COMMINVERSEKINEMATICSREQUEST_H_ */
