//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#include "CommManipulatorObjects/CommCartesianManipulationTarget.hh"

using namespace CommManipulatorObjects;

CommCartesianManipulationTarget::CommCartesianManipulationTarget()
:	CommCartesianManipulationTargetCore()
{  }


/**
 * Constructor to set all values.
 * NOTE that you have to keep this constructor consistent with the model!
 * Use  at your own choice.
 *
 * The preferred way to set values for initialization is:
 *      CommRepository::MyCommObject obj;
 *      obj.setX(1).setY(2).setZ(3)...;
CommCartesianManipulationTarget::CommCartesianManipulationTarget(const CommBasicObjects::CommPose3d &tcp_pose, const CommManipulatorObjects::BasicRobotMotionType &motion_type, const CommManipulatorObjects::TargetVelocityTimeFlag &reach_type, const float &velocity, const float &acceleration, const unsigned char &motion_constraints, const bool &is_relative, const float &reach_time, const float &blending_radius)
:	CommCartesianManipulationTargetCore() // base constructor sets default values as defined in the model
{
	setTcp_pose(tcp_pose);
	setIs_relative(is_relative);
	setMotion_type(motion_type);
	setReach_type(reach_type);
	setVelocity(velocity);
	setAcceleration(acceleration);
	setReach_time(reach_time);
	setBlending_radius(blending_radius);
	setMotion_constraints(motion_constraints);
}
 */

CommCartesianManipulationTarget::CommCartesianManipulationTarget(const CommCartesianManipulationTargetCore &commCartesianManipulationTarget)
:	CommCartesianManipulationTargetCore(commCartesianManipulationTarget)
{  }

CommCartesianManipulationTarget::CommCartesianManipulationTarget(const DATATYPE &commCartesianManipulationTarget)
:	CommCartesianManipulationTargetCore(commCartesianManipulationTarget)
{  }

CommCartesianManipulationTarget::~CommCartesianManipulationTarget()
{  }
