//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_ROBOTINODOCKINGEVENTTYPE_ENUM_H_
#define COMMROBOTINOOBJECTS_ROBOTINODOCKINGEVENTTYPE_ENUM_H_

#include <CommRobotinoObjects/enumRobotinoDockingEventTypeData.hh>

#include <string>
#include <iostream>
#include <locale>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace CommRobotinoObjects {
	
	class RobotinoDockingEventType {
	private:
		CommRobotinoObjectsIDL::RobotinoDockingEventType value;
		
	public:
		enum ENUM_RobotinoDockingEventType {
			ENUM_VALUE_UNDEFINED = 0,
			DOCKING_UNKNOWN = 1,
			IR_DOCKING_DONE = 2,
			LASER_DOCKING_DONE = 3,
			IR_DOCKING_NOT_DONE = 4,
			LASER_DOCKING_NOT_DONE = 5,
			LASER_DOCKING_ERROR = 6,
			IR_DOCKING_ERROR = 7,
			UN_DOCKING_NOT_DONE = 8,
			UN_DOCKING_DONE = 9,
			UN_DOCKING_ERROR = 10
		};
		
		// default constructor
		RobotinoDockingEventType() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		RobotinoDockingEventType(ENUM_RobotinoDockingEventType e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type (which is typically int)
		RobotinoDockingEventType(CommRobotinoObjectsIDL::RobotinoDockingEventType e) {
			value = e;
		}
		
		//const CommRobotinoObjectsIDL::RobotinoDockingEventType& get() const { return value; }
		
		// ENUM operator
		operator ENUM_RobotinoDockingEventType() const {
			return static_cast<ENUM_RobotinoDockingEventType>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_RobotinoDockingEventType t) const {
			return this->value == t;
		}
		
		std::string to_string(const bool &use_fqn=true) const {
			std::string result = "";
			if(use_fqn == true) {
				result = "RobotinoDockingEventType::";
			}
			switch (value) {
				case DOCKING_UNKNOWN:
					result += "DOCKING_UNKNOWN";
					break;
				case IR_DOCKING_DONE:
					result += "IR_DOCKING_DONE";
					break;
				case LASER_DOCKING_DONE:
					result += "LASER_DOCKING_DONE";
					break;
				case IR_DOCKING_NOT_DONE:
					result += "IR_DOCKING_NOT_DONE";
					break;
				case LASER_DOCKING_NOT_DONE:
					result += "LASER_DOCKING_NOT_DONE";
					break;
				case LASER_DOCKING_ERROR:
					result += "LASER_DOCKING_ERROR";
					break;
				case IR_DOCKING_ERROR:
					result += "IR_DOCKING_ERROR";
					break;
				case UN_DOCKING_NOT_DONE:
					result += "UN_DOCKING_NOT_DONE";
					break;
				case UN_DOCKING_DONE:
					result += "UN_DOCKING_DONE";
					break;
				case UN_DOCKING_ERROR:
					result += "UN_DOCKING_ERROR";
					break;
				default:
					result += "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		static RobotinoDockingEventType from_string(const std::string &value) {
			std::string input = value;
			std::locale l;
			for(auto &c: input) {
				// convert all characters to lower case (so string comparison works regardless of small/capital letters)
				c = std::tolower(c,l);
			}
			std::string base_name = "robotinodockingeventtype::";
			if(input.compare(0, base_name.length(), base_name) == 0) {
				// remove basename from comparing the actual enumeration
				input.erase(0,base_name.length());
			}
			if(input == "docking_unknown"){
				return RobotinoDockingEventType(DOCKING_UNKNOWN);
			}
			if(input == "ir_docking_done"){
				return RobotinoDockingEventType(IR_DOCKING_DONE);
			}
			if(input == "laser_docking_done"){
				return RobotinoDockingEventType(LASER_DOCKING_DONE);
			}
			if(input == "ir_docking_not_done"){
				return RobotinoDockingEventType(IR_DOCKING_NOT_DONE);
			}
			if(input == "laser_docking_not_done"){
				return RobotinoDockingEventType(LASER_DOCKING_NOT_DONE);
			}
			if(input == "laser_docking_error"){
				return RobotinoDockingEventType(LASER_DOCKING_ERROR);
			}
			if(input == "ir_docking_error"){
				return RobotinoDockingEventType(IR_DOCKING_ERROR);
			}
			if(input == "un_docking_not_done"){
				return RobotinoDockingEventType(UN_DOCKING_NOT_DONE);
			}
			if(input == "un_docking_done"){
				return RobotinoDockingEventType(UN_DOCKING_DONE);
			}
			if(input == "un_docking_error"){
				return RobotinoDockingEventType(UN_DOCKING_ERROR);
			}
			// default (if none of the preceding options match)
			return RobotinoDockingEventType();
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const RobotinoDockingEventType &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
