//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "ForkliftEventStateJSON.hh"

#include <DomainForklift/enumForkliftEventType.hh>

namespace DomainForkliftIDL {

void to_json(const DomainForkliftIDL::ForkliftEventState& obj, nlohmann::json& j)
{
	// newState: ForkliftEventType
	j["newState"] = DomainForklift::ForkliftEventType(obj.newState).to_string(false);
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, DomainForkliftIDL::ForkliftEventState& obj)
{
	// newState: ForkliftEventType
	if(j.contains("newState") && j["newState"].is_string()) {
		obj.newState = DomainForklift::ForkliftEventType::from_string(j["newState"].get<std::string>());
	}
}

} // end namespace DomainForkliftIDL
