//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainPrint/CommPrintResponseACE.hh"
#include <ace/SString.h>
#include "DomainPrint/enumPrintResponseResultEnumData.hh"

// serialization operator for element CommPrintResponse
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainPrintIDL::CommPrintResponse &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element resultValue
	good_bit = good_bit && cdr << ACE_CString(data.resultValue.c_str());
	// serialize list-element result
	good_bit = good_bit && cdr.write_long(data.result);
	
	return good_bit;
}

// de-serialization operator for element CommPrintResponse
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainPrintIDL::CommPrintResponse &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize string-type element resultValue
	ACE_CString data_resultValue_str;
	good_bit = good_bit && cdr >> data_resultValue_str;
	data.resultValue = data_resultValue_str.c_str();
	// deserialize type element result
	good_bit = good_bit && cdr.read_long(data.result);
	
	return good_bit;
}

// serialization operator for CommunicationObject CommPrintResponse
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainPrint::CommPrintResponse &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommPrintResponse
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainPrint::CommPrintResponse &obj)
{
	return cdr >> obj.set();
}
