//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainPrint/CommPrinterStatusACE.hh"
#include <ace/SString.h>
#include "DomainPrint/enumPrinterStatusEnumData.hh"

// serialization operator for element CommPrinterStatus
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainPrintIDL::CommPrinterStatus &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element status
	good_bit = good_bit && cdr.write_long(data.status);
	// serialize list-element statusRIBWARN
	good_bit = good_bit && cdr.write_boolean(data.statusRIBWARN);
	// serialize list-element statusLBLWARN
	good_bit = good_bit && cdr.write_boolean(data.statusLBLWARN);
	
	return good_bit;
}

// de-serialization operator for element CommPrinterStatus
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainPrintIDL::CommPrinterStatus &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element status
	good_bit = good_bit && cdr.read_long(data.status);
	// deserialize type element statusRIBWARN
	good_bit = good_bit && cdr.read_boolean(data.statusRIBWARN);
	// deserialize type element statusLBLWARN
	good_bit = good_bit && cdr.read_boolean(data.statusLBLWARN);
	
	return good_bit;
}

// serialization operator for CommunicationObject CommPrinterStatus
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainPrint::CommPrinterStatus &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommPrinterStatus
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainPrint::CommPrinterStatus &obj)
{
	return cdr >> obj.set();
}
