//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINPRINT_COMMPRINTRESPONSE_CORE_H_
#define DOMAINPRINT_COMMPRINTRESPONSE_CORE_H_

#include "DomainPrint/CommPrintResponseData.hh"
#include "DomainPrint/enumPrintResponseResultEnum.hh"

#include <iostream>
#include <string>
#include <list>

namespace DomainPrint {
	
class CommPrintResponseCore {
protected:
	// data structure
	DomainPrintIDL::CommPrintResponse idl_CommPrintResponse;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef DomainPrintIDL::CommPrintResponse DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommPrintResponseCore();
	CommPrintResponseCore(const DATATYPE &data);
	// default destructor
	virtual ~CommPrintResponseCore();
	
	const DATATYPE& get() const { return idl_CommPrintResponse; }
	operator const DATATYPE&() const { return idl_CommPrintResponse; }
	DATATYPE& set() { return idl_CommPrintResponse; }

	static inline std::string identifier(void) { return "DomainPrint::CommPrintResponse"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element ResultValue
	inline std::string getResultValue() const { return idl_CommPrintResponse.resultValue; }
	inline CommPrintResponseCore& setResultValue(const std::string &resultValue) { idl_CommPrintResponse.resultValue = resultValue; return *this; }
	
	// getter and setter for element Result
	inline DomainPrint::PrintResponseResultEnum getResult() const { return DomainPrint::PrintResponseResultEnum(idl_CommPrintResponse.result); }
	inline CommPrintResponseCore& setResult(const DomainPrint::PrintResponseResultEnum &result) { idl_CommPrintResponse.result = result; return *this; }
};

} /* namespace DomainPrint */
#endif /* DOMAINPRINT_COMMPRINTRESPONSE_CORE_H_ */
