//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINPRINT_COMMPRINTPROCESSDATA_DATA_H_
#define DOMAINPRINT_COMMPRINTPROCESSDATA_DATA_H_

#include "DomainPrint/CommKeyValueData.hh"
#include "DomainPrint/enumApplicationModeTypeEnumData.hh"

#include <vector>
#include <string>

namespace DomainPrintIDL 
{
	typedef std::vector<DomainPrintIDL::CommKeyValue> CommPrintProcessData_data_type;
	struct CommPrintProcessData
	{
		CommPrintProcessData_data_type data;
		std::string templateID;
		DomainPrintIDL::ApplicationModeTypeEnum applicationMode;
  	};
};

#endif /* DOMAINPRINT_COMMPRINTPROCESSDATA_DATA_H_ */
