//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINPRINT_PRINTERSTATUSENUM_ENUM_H_
#define DOMAINPRINT_PRINTERSTATUSENUM_ENUM_H_

#include <DomainPrint/enumPrinterStatusEnumData.hh>

#include <string>
#include <iostream>
#include <locale>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace DomainPrint {
	
	class PrinterStatusEnum {
	private:
		DomainPrintIDL::PrinterStatusEnum value;
		
	public:
		enum ENUM_PrinterStatusEnum {
			ENUM_VALUE_UNDEFINED = 0,
			IDLE = 1,
			BUSY = 2,
			ERROR = 3
		};
		
		// default constructor
		PrinterStatusEnum() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		PrinterStatusEnum(ENUM_PrinterStatusEnum e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type (which is typically int)
		PrinterStatusEnum(DomainPrintIDL::PrinterStatusEnum e) {
			value = e;
		}
		
		//const DomainPrintIDL::PrinterStatusEnum& get() const { return value; }
		
		// ENUM operator
		operator ENUM_PrinterStatusEnum() const {
			return static_cast<ENUM_PrinterStatusEnum>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_PrinterStatusEnum t) const {
			return this->value == t;
		}
		
		std::string to_string(const bool &use_fqn=true) const {
			std::string result = "";
			if(use_fqn == true) {
				result = "PrinterStatusEnum::";
			}
			switch (value) {
				case IDLE:
					result += "IDLE";
					break;
				case BUSY:
					result += "BUSY";
					break;
				case ERROR:
					result += "ERROR";
					break;
				default:
					result += "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		static PrinterStatusEnum from_string(const std::string &value) {
			std::string input = value;
			std::locale l;
			for(auto &c: input) {
				// convert all characters to lower case (so string comparison works regardless of small/capital letters)
				c = std::tolower(c,l);
			}
			std::string base_name = "printerstatusenum::";
			if(input.compare(0, base_name.length(), base_name) == 0) {
				// remove basename from comparing the actual enumeration
				input.erase(0,base_name.length());
			}
			if(input == "idle"){
				return PrinterStatusEnum(IDLE);
			}
			if(input == "busy"){
				return PrinterStatusEnum(BUSY);
			}
			if(input == "error"){
				return PrinterStatusEnum(ERROR);
			}
			// default (if none of the preceding options match)
			return PrinterStatusEnum();
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const PrinterStatusEnum &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
