//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINPTU_PTUMOVEFLAG_ENUM_H_
#define DOMAINPTU_PTUMOVEFLAG_ENUM_H_

#include <DomainPTU/enumPTUMoveFlagData.hh>

#include <string>
#include <iostream>
#include <locale>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace DomainPTU {
	
	class PTUMoveFlag {
	private:
		DomainPTUIDL::PTUMoveFlag value;
		
	public:
		enum ENUM_PTUMoveFlag {
			ENUM_VALUE_UNDEFINED = 0,
			PAN_RELATIVE = 1,
			PAN_ABSOLUTE = 2,
			TILT_RELATIVE = 3,
			TILT_ABSOLUTE = 4,
			PAN_TILT_RELATIVE = 5,
			PAN_TILT_ABSOLUTE = 6,
			POSITION_ROBOT = 7,
			POSITION_WORLD = 8
		};
		
		// default constructor
		PTUMoveFlag() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		PTUMoveFlag(ENUM_PTUMoveFlag e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type (which is typically int)
		PTUMoveFlag(DomainPTUIDL::PTUMoveFlag e) {
			value = e;
		}
		
		//const DomainPTUIDL::PTUMoveFlag& get() const { return value; }
		
		// ENUM operator
		operator ENUM_PTUMoveFlag() const {
			return static_cast<ENUM_PTUMoveFlag>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_PTUMoveFlag t) const {
			return this->value == t;
		}
		
		std::string to_string(const bool &use_fqn=true) const {
			std::string result = "";
			if(use_fqn == true) {
				result = "PTUMoveFlag::";
			}
			switch (value) {
				case PAN_RELATIVE:
					result += "PAN_RELATIVE";
					break;
				case PAN_ABSOLUTE:
					result += "PAN_ABSOLUTE";
					break;
				case TILT_RELATIVE:
					result += "TILT_RELATIVE";
					break;
				case TILT_ABSOLUTE:
					result += "TILT_ABSOLUTE";
					break;
				case PAN_TILT_RELATIVE:
					result += "PAN_TILT_RELATIVE";
					break;
				case PAN_TILT_ABSOLUTE:
					result += "PAN_TILT_ABSOLUTE";
					break;
				case POSITION_ROBOT:
					result += "POSITION_ROBOT";
					break;
				case POSITION_WORLD:
					result += "POSITION_WORLD";
					break;
				default:
					result += "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		static PTUMoveFlag from_string(const std::string &value) {
			std::string input = value;
			std::locale l;
			for(auto &c: input) {
				// convert all characters to lower case (so string comparison works regardless of small/capital letters)
				c = std::tolower(c,l);
			}
			std::string base_name = "ptumoveflag::";
			if(input.compare(0, base_name.length(), base_name) == 0) {
				// remove basename from comparing the actual enumeration
				input.erase(0,base_name.length());
			}
			if(input == "pan_relative"){
				return PTUMoveFlag(PAN_RELATIVE);
			}
			if(input == "pan_absolute"){
				return PTUMoveFlag(PAN_ABSOLUTE);
			}
			if(input == "tilt_relative"){
				return PTUMoveFlag(TILT_RELATIVE);
			}
			if(input == "tilt_absolute"){
				return PTUMoveFlag(TILT_ABSOLUTE);
			}
			if(input == "pan_tilt_relative"){
				return PTUMoveFlag(PAN_TILT_RELATIVE);
			}
			if(input == "pan_tilt_absolute"){
				return PTUMoveFlag(PAN_TILT_ABSOLUTE);
			}
			if(input == "position_robot"){
				return PTUMoveFlag(POSITION_ROBOT);
			}
			if(input == "position_world"){
				return PTUMoveFlag(POSITION_WORLD);
			}
			// default (if none of the preceding options match)
			return PTUMoveFlag();
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const PTUMoveFlag &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
