//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMBASICOBJECTS_SAFETYFIELDSTATE_ENUM_H_
#define COMMBASICOBJECTS_SAFETYFIELDSTATE_ENUM_H_

#include <CommBasicObjects/enumSafetyFieldStateData.hh>

#include <string>
#include <iostream>
#include <locale>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace CommBasicObjects {
	
	class SafetyFieldState {
	private:
		CommBasicObjectsIDL::SafetyFieldState value;
		
	public:
		enum ENUM_SafetyFieldState {
			ENUM_VALUE_UNDEFINED = 0,
			FREE = 1,
			BLOCKED = 2,
			UNKNOWN = 3
		};
		
		// default constructor
		SafetyFieldState() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		SafetyFieldState(ENUM_SafetyFieldState e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type (which is typically int)
		SafetyFieldState(CommBasicObjectsIDL::SafetyFieldState e) {
			value = e;
		}
		
		//const CommBasicObjectsIDL::SafetyFieldState& get() const { return value; }
		
		// ENUM operator
		operator ENUM_SafetyFieldState() const {
			return static_cast<ENUM_SafetyFieldState>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_SafetyFieldState t) const {
			return this->value == t;
		}
		
		std::string to_string(const bool &use_fqn=true) const {
			std::string result = "";
			if(use_fqn == true) {
				result = "SafetyFieldState::";
			}
			switch (value) {
				case FREE:
					result += "FREE";
					break;
				case BLOCKED:
					result += "BLOCKED";
					break;
				case UNKNOWN:
					result += "UNKNOWN";
					break;
				default:
					result += "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		static SafetyFieldState from_string(const std::string &value) {
			std::string input = value;
			std::locale l;
			for(auto &c: input) {
				// convert all characters to lower case (so string comparison works regardless of small/capital letters)
				c = std::tolower(c,l);
			}
			std::string base_name = "safetyfieldstate::";
			if(input.compare(0, base_name.length(), base_name) == 0) {
				// remove basename from comparing the actual enumeration
				input.erase(0,base_name.length());
			}
			if(input == "free"){
				return SafetyFieldState(FREE);
			}
			if(input == "blocked"){
				return SafetyFieldState(BLOCKED);
			}
			if(input == "unknown"){
				return SafetyFieldState(UNKNOWN);
			}
			// default (if none of the preceding options match)
			return SafetyFieldState();
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const SafetyFieldState &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
