//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMBASICOBJECTS_BUMPEREVENTTYPE_ENUM_H_
#define COMMBASICOBJECTS_BUMPEREVENTTYPE_ENUM_H_

#include <CommBasicObjects/enumBumperEventTypeData.hh>

#include <string>
#include <iostream>
#include <locale>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace CommBasicObjects {
	
	class BumperEventType {
	private:
		CommBasicObjectsIDL::BumperEventType value;
		
	public:
		enum ENUM_BumperEventType {
			ENUM_VALUE_UNDEFINED = 0,
			BUMPER_UNKNOWN = 1,
			BUMPER_NOT_PRESSED = 2,
			BUMPER_PRESSED = 3
		};
		
		// default constructor
		BumperEventType() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		BumperEventType(ENUM_BumperEventType e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type (which is typically int)
		BumperEventType(CommBasicObjectsIDL::BumperEventType e) {
			value = e;
		}
		
		//const CommBasicObjectsIDL::BumperEventType& get() const { return value; }
		
		// ENUM operator
		operator ENUM_BumperEventType() const {
			return static_cast<ENUM_BumperEventType>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_BumperEventType t) const {
			return this->value == t;
		}
		
		std::string to_string(const bool &use_fqn=true) const {
			std::string result = "";
			if(use_fqn == true) {
				result = "BumperEventType::";
			}
			switch (value) {
				case BUMPER_UNKNOWN:
					result += "BUMPER_UNKNOWN";
					break;
				case BUMPER_NOT_PRESSED:
					result += "BUMPER_NOT_PRESSED";
					break;
				case BUMPER_PRESSED:
					result += "BUMPER_PRESSED";
					break;
				default:
					result += "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		static BumperEventType from_string(const std::string &value) {
			std::string input = value;
			std::locale l;
			for(auto &c: input) {
				// convert all characters to lower case (so string comparison works regardless of small/capital letters)
				c = std::tolower(c,l);
			}
			std::string base_name = "bumpereventtype::";
			if(input.compare(0, base_name.length(), base_name) == 0) {
				// remove basename from comparing the actual enumeration
				input.erase(0,base_name.length());
			}
			if(input == "bumper_unknown"){
				return BumperEventType(BUMPER_UNKNOWN);
			}
			if(input == "bumper_not_pressed"){
				return BumperEventType(BUMPER_NOT_PRESSED);
			}
			if(input == "bumper_pressed"){
				return BumperEventType(BUMPER_PRESSED);
			}
			// default (if none of the preceding options match)
			return BumperEventType();
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const BumperEventType &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
