//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommManipulatorObjects/CommJointManipulationTargetCore.hh"

// serialization/deserialization operators
//#include "CommManipulatorObjects/CommJointManipulationTargetACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace CommManipulatorObjects 
{
	const char* CommJointManipulationTargetCore::getCompiledHash()
	{
		return CommManipulatorObjectsIDL::REPO_HASH;
	}
	
	void CommJointManipulationTargetCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
	}
	
	void CommJointManipulationTargetCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommJointManipulationTargetCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
	}
	
	#ifdef ENABLE_HASH
	size_t CommJointManipulationTargetCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		std::vector<ACE_CDR::Float>::const_iterator data_joint_anglesIt;
		for(data_joint_anglesIt=data.joint_angles.begin(); data_joint_anglesIt!=data.joint_angles.end(); data_joint_anglesIt++) {
			boost::hash_combine(seed, *data_joint_anglesIt);
		}
		boost::hash_combine(seed, data.is_relative);
		boost::hash_combine(seed, data.motion_type);
		boost::hash_combine(seed, data.reach_type);
		boost::hash_combine(seed, data.velocity);
		boost::hash_combine(seed, data.acceleration);
		boost::hash_combine(seed, data.reach_time);
		boost::hash_combine(seed, data.blending_radius);
		
		return seed;
	}
	#endif
	
	// default constructor
	CommJointManipulationTargetCore::CommJointManipulationTargetCore()
	:	idl_CommJointManipulationTarget()
	{  
		setJoint_angles(std::vector<float>());
		setIs_relative(false);
		setMotion_type(CommManipulatorObjects::BasicRobotMotionType());
		setReach_type(CommManipulatorObjects::TargetVelocityTimeFlag());
		setVelocity(0.0);
		setAcceleration(0.0);
		setReach_time(0.0);
		setBlending_radius(0.0);
	}
	
	CommJointManipulationTargetCore::CommJointManipulationTargetCore(const DATATYPE &data)
	:	idl_CommJointManipulationTarget(data)
	{  }

	CommJointManipulationTargetCore::~CommJointManipulationTargetCore()
	{  }
	
	void CommJointManipulationTargetCore::to_ostream(std::ostream &os) const
	{
	  os << "CommJointManipulationTarget(";
	  std::vector<float>::const_iterator joint_anglesIt;
	  std::vector<float> joint_anglesList = getJoint_anglesCopy();
	  for(joint_anglesIt=joint_anglesList.begin(); joint_anglesIt!=joint_anglesList.end(); joint_anglesIt++) {
	  	os << *joint_anglesIt << " ";
	  }
	  os << getIs_relative() << " ";
	  getMotion_type().to_ostream(os);
	  getReach_type().to_ostream(os);
	  os << getVelocity() << " ";
	  os << getAcceleration() << " ";
	  os << getReach_time() << " ";
	  os << getBlending_radius() << " ";
	  os << ") ";
	}
	
	// convert to xml stream
	void CommJointManipulationTargetCore::to_xml(std::ostream &os, const std::string &indent) const {
		size_t counter = 0;
		
		std::vector<float>::const_iterator joint_anglesIt;
		std::vector<float> joint_anglesList = getJoint_anglesCopy();
		counter = 0;
		os << indent << "<joint_anglesList n=\"" << joint_anglesList.size() << "\">";
		for(joint_anglesIt=joint_anglesList.begin(); joint_anglesIt!=joint_anglesList.end(); joint_anglesIt++) {
			os << indent << "<joint_angles i=\"" << counter++ << "\">" << *joint_anglesIt << "</joint_angles>";
		}
		os << indent << "</joint_anglesList>";
		os << indent << "<is_relative>" << getIs_relative() << "</is_relative>";
		os << indent << "<motion_type>";
		getMotion_type().to_xml(os, indent);
		os << indent << "</motion_type>";
		os << indent << "<reach_type>";
		getReach_type().to_xml(os, indent);
		os << indent << "</reach_type>";
		os << indent << "<velocity>" << getVelocity() << "</velocity>";
		os << indent << "<acceleration>" << getAcceleration() << "</acceleration>";
		os << indent << "<reach_time>" << getReach_time() << "</reach_time>";
		os << indent << "<blending_radius>" << getBlending_radius() << "</blending_radius>";
	}
	
	// restore from xml stream
	void CommJointManipulationTargetCore::from_xml(std::istream &is) {
		size_t counter = 0;
		
		static const Smart::KnuthMorrisPratt kmp_joint_anglesList("<joint_anglesList n=\"");
		static const Smart::KnuthMorrisPratt kmp_joint_angles("\">");
		static const Smart::KnuthMorrisPratt kmp_is_relative("<is_relative>");
		static const Smart::KnuthMorrisPratt kmp_motion_type("<motion_type>");
		static const Smart::KnuthMorrisPratt kmp_reach_type("<reach_type>");
		static const Smart::KnuthMorrisPratt kmp_velocity("<velocity>");
		static const Smart::KnuthMorrisPratt kmp_acceleration("<acceleration>");
		static const Smart::KnuthMorrisPratt kmp_reach_time("<reach_time>");
		static const Smart::KnuthMorrisPratt kmp_blending_radius("<blending_radius>");
		
		if(kmp_joint_anglesList.search(is)) {
			size_t numberElements;
			is >> numberElements;
			float joint_anglesItem;
			std::vector<float> joint_anglesList;
			kmp_joint_angles.search(is);
			for(counter=0; counter<numberElements; counter++) {
				if(kmp_joint_angles.search(is)) {
					is >> joint_anglesItem;
					joint_anglesList.push_back(joint_anglesItem);
				}
			}
			setJoint_angles(joint_anglesList);
		}
		if(kmp_is_relative.search(is)) {
			bool is_relativeItem;
			is >> is_relativeItem;
			setIs_relative(is_relativeItem);
		}
		if(kmp_motion_type.search(is)) {
			CommManipulatorObjects::BasicRobotMotionType motion_typeItem;
			motion_typeItem.from_xml(is);
			setMotion_type(motion_typeItem);
		}
		if(kmp_reach_type.search(is)) {
			CommManipulatorObjects::TargetVelocityTimeFlag reach_typeItem;
			reach_typeItem.from_xml(is);
			setReach_type(reach_typeItem);
		}
		if(kmp_velocity.search(is)) {
			float velocityItem;
			is >> velocityItem;
			setVelocity(velocityItem);
		}
		if(kmp_acceleration.search(is)) {
			float accelerationItem;
			is >> accelerationItem;
			setAcceleration(accelerationItem);
		}
		if(kmp_reach_time.search(is)) {
			float reach_timeItem;
			is >> reach_timeItem;
			setReach_time(reach_timeItem);
		}
		if(kmp_blending_radius.search(is)) {
			float blending_radiusItem;
			is >> blending_radiusItem;
			setBlending_radius(blending_radiusItem);
		}
	}
	
	/*
	void CommJointManipulationTargetCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		CommManipulatorObjectsIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(CommManipulatorObjectsIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommJointManipulationTargetACE.hh)
		cdr << idl_CommJointManipulationTarget;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommJointManipulationTarget);
		cdr << data_hash;
		// std::cout << "CommJointManipulationTargetCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommJointManipulationTargetCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		CommManipulatorObjectsIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommJointManipulationTargetACE.hh)
		cdr >> idl_CommJointManipulationTarget;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommJointManipulationTarget);
		assert(data_hash == own_hash);
		// std::cout << "CommJointManipulationTargetCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace CommManipulatorObjects */
