//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMMANIPULATOROBJECTS_COMMMANIPULATIONTRAJECTORY_DATA_H_
#define COMMMANIPULATOROBJECTS_COMMMANIPULATIONTRAJECTORY_DATA_H_

#include "CommManipulatorObjects/CommCartesianManipulationTargetData.hh"
#include "CommManipulatorObjects/enumManipulatorTrajectoryFlagData.hh"
#include "CommManipulatorObjects/CommJointManipulationTargetData.hh"

#include <vector>

namespace CommManipulatorObjectsIDL 
{
	typedef std::vector<CommManipulatorObjectsIDL::CommJointManipulationTarget> CommManipulationTrajectory_joint_angles_type;
	typedef std::vector<CommManipulatorObjectsIDL::CommCartesianManipulationTarget> CommManipulationTrajectory_tcp_poses_type;
	struct CommManipulationTrajectory
	{
		CommManipulationTrajectory_joint_angles_type joint_angles;
		CommManipulationTrajectory_tcp_poses_type tcp_poses;
		CommManipulatorObjectsIDL::ManipulatorTrajectoryFlag type;
  	};
};

#endif /* COMMMANIPULATOROBJECTS_COMMMANIPULATIONTRAJECTORY_DATA_H_ */
