//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMMANIPULATOROBJECTS_COMMVACUMMGRIPPERSTATE_CORE_H_
#define COMMMANIPULATOROBJECTS_COMMVACUMMGRIPPERSTATE_CORE_H_

#include "CommManipulatorObjects/CommVacummGripperStateData.hh"
#include "CommManipulatorObjects/enumVacuumGraspState.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommManipulatorObjects {
	
class CommVacummGripperStateCore {
protected:
	// data structure
	CommManipulatorObjectsIDL::CommVacummGripperState idl_CommVacummGripperState;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommManipulatorObjectsIDL::CommVacummGripperState DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommVacummGripperStateCore();
	CommVacummGripperStateCore(const DATATYPE &data);
	// default destructor
	virtual ~CommVacummGripperStateCore();
	
	const DATATYPE& get() const { return idl_CommVacummGripperState; }
	operator const DATATYPE&() const { return idl_CommVacummGripperState; }
	DATATYPE& set() { return idl_CommVacummGripperState; }

	static inline std::string identifier(void) { return "CommManipulatorObjects::CommVacummGripperState"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element State
	inline CommManipulatorObjects::VacuumGraspState getState() const { return CommManipulatorObjects::VacuumGraspState(idl_CommVacummGripperState.state); }
	inline CommVacummGripperStateCore& setState(const CommManipulatorObjects::VacuumGraspState &state) { idl_CommVacummGripperState.state = state; return *this; }
	
	// getter and setter for element VacuumLevel
	inline double getVacuumLevel() const { return idl_CommVacummGripperState.vacuumLevel; }
	inline CommVacummGripperStateCore& setVacuumLevel(const double &vacuumLevel) { idl_CommVacummGripperState.vacuumLevel = vacuumLevel; return *this; }
};

} /* namespace CommManipulatorObjects */
#endif /* COMMMANIPULATOROBJECTS_COMMVACUMMGRIPPERSTATE_CORE_H_ */
