//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMMANIPULATOROBJECTS_COMMVACUUMGRIPPEREVENTPARAMETER_CORE_H_
#define COMMMANIPULATOROBJECTS_COMMVACUUMGRIPPEREVENTPARAMETER_CORE_H_

#include "CommManipulatorObjects/CommVacuumGripperEventParameterData.hh"
#include "CommManipulatorObjects/enumVacuumGraspState.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommManipulatorObjects {
	
class CommVacuumGripperEventParameterCore {
protected:
	// data structure
	CommManipulatorObjectsIDL::CommVacuumGripperEventParameter idl_CommVacuumGripperEventParameter;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommManipulatorObjectsIDL::CommVacuumGripperEventParameter DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommVacuumGripperEventParameterCore();
	CommVacuumGripperEventParameterCore(const DATATYPE &data);
	// default destructor
	virtual ~CommVacuumGripperEventParameterCore();
	
	const DATATYPE& get() const { return idl_CommVacuumGripperEventParameter; }
	operator const DATATYPE&() const { return idl_CommVacuumGripperEventParameter; }
	DATATYPE& set() { return idl_CommVacuumGripperEventParameter; }

	static inline std::string identifier(void) { return "CommManipulatorObjects::CommVacuumGripperEventParameter"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element State
	inline CommManipulatorObjects::VacuumGraspState getState() const { return CommManipulatorObjects::VacuumGraspState(idl_CommVacuumGripperEventParameter.state); }
	inline CommVacuumGripperEventParameterCore& setState(const CommManipulatorObjects::VacuumGraspState &state) { idl_CommVacuumGripperEventParameter.state = state; return *this; }
};

} /* namespace CommManipulatorObjects */
#endif /* COMMMANIPULATOROBJECTS_COMMVACUUMGRIPPEREVENTPARAMETER_CORE_H_ */
