//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINEXTERNALSYSTEMS_COMMEXTERNALPROGRAMRESPONSE_H_
#define DOMAINEXTERNALSYSTEMS_COMMEXTERNALPROGRAMRESPONSE_H_

#include "DomainExternalSystems/CommExternalProgramResponseCore.hh"

namespace DomainExternalSystems {
		
class CommExternalProgramResponse : public CommExternalProgramResponseCore {
	public:
		// default constructors
		CommExternalProgramResponse();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommExternalProgramResponse(const DomainExternalSystems::ExternalProgramStatus &status, const DomainExternalSystems::ExternalProgramResult &result, const std::vector<DomainExternalSystems::CommExternalProgramArgument> &resultArgs);
		
		CommExternalProgramResponse(const CommExternalProgramResponseCore &commExternalProgramResponse);
		CommExternalProgramResponse(const DATATYPE &commExternalProgramResponse);
		virtual ~CommExternalProgramResponse();
		
		// use framework specific getter and setter methods from core (base) class
		using CommExternalProgramResponseCore::get;
		using CommExternalProgramResponseCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommExternalProgramResponse &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace DomainExternalSystems */
#endif /* DOMAINEXTERNALSYSTEMS_COMMEXTERNALPROGRAMRESPONSE_H_ */
