//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommObjectRFIDReadJSON.hh"


namespace CommObjectRecognitionObjectsIDL {

void to_json(const CommObjectRecognitionObjectsIDL::CommObjectRFIDRead& obj, nlohmann::json& j)
{
	// tagId: String
	j["tagId"] = obj.tagId;
	// rssi: Int32
	j["rssi"] = obj.rssi;
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, CommObjectRecognitionObjectsIDL::CommObjectRFIDRead& obj)
{
	// tagId: String
	if(j.contains("tagId") && j["tagId"].is_string()) {
		obj.tagId = j["tagId"].get<std::string>();
	}
	// rssi: Int32
	if(j.contains("rssi") && j["rssi"].is_number_integer()) {
		obj.rssi = j["rssi"].get<int>();
	}
}

} // end namespace CommObjectRecognitionObjectsIDL
