//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "OcrEventStateJSON.hh"


namespace CommObjectRecognitionObjectsIDL {

void to_json(const CommObjectRecognitionObjectsIDL::OcrEventState& obj, nlohmann::json& j)
{
	// environment_id: Int32
	j["environment_id"] = obj.environment_id;
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, CommObjectRecognitionObjectsIDL::OcrEventState& obj)
{
	// environment_id: Int32
	if(j.contains("environment_id") && j["environment_id"].is_number_integer()) {
		obj.environment_id = j["environment_id"].get<int>();
	}
}

} // end namespace CommObjectRecognitionObjectsIDL
